Update logging.md
unoplatform/uno pull request #10100
Opened 2022-10-09 15:01 UTC by IrvinDominin

Fixed #if indentation in md file for a better reading

GitHub Issue (If applicable): closes #10099

## PR Type

Corrected the indentation

## What is the current behavior?

The #if markdows is not correct for displaying

## What is the new behavior?

The #if markdows is now correct

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

2022-10-09 15:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/unoplatform/uno?pullRequest=10100) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/unoplatform/uno?pullRequest=10100) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unoplatform/uno?pullRequest=10100) it.</sub>

2022-10-09 22:12 UTC, Youssef1313 requested changes
~~Old indentation looks correct to me.~~

2022-10-09 22:16 UTC, Youssef1313 approved these changes
Oh I see now that the whole code fence is indented. LGTM.

2022-10-11 01:23 UTC, jeromelaban commented
@IrvinDominin Thanks for your contribution! The commit name needs to start with `docs:`, so yours should be `docs: Fix logging indentation for markdown formatting`. Could you rewrite it?

2022-10-11 05:05 UTC, IrvinDominin commented
@jeromelaban ops sorry, done!

2022-10-11 06:41 UTC, Youssef1313 commented
@IrvinDominin You only changed PR title, but commit message is still the same.

2022-10-11 08:08 UTC, IrvinDominin commented
> @IrvinDominin You only changed PR title, but commit message is still the same.

Hi @Youssef1313 can you please point me in the rigth direction to change it?

2022-10-11 10:12 UTC, Youssef1313 commented
> > @IrvinDominin You only changed PR title, but commit message is still the same.
> 
> Hi @Youssef1313 can you please point me in the rigth direction to change it?

#### From the command line

1. Clone the repository locally if you haven't already (`git clone https://github.com/IrvinDominin/uno.git`)
2. Checkout the branch via `git checkout patch-1` (if this didn't work, do `git fetch origin` first)
3. Remove your last merge commit with `get reset --hard HEAD~1`
4. Modify the message of last commit with `git commit --amend -m "docs: Fix logging indentation for markdown formatting"`

2022-10-12 17:37 UTC, jeromelaban approved these changes

2022-10-12 18:19 UTC, merged