ci: Bump to net7 RC2 with mobile
unoplatform/uno pull request #10200
Opened 2022-10-19 13:54 UTC by jeromelaban

2022-10-20 00:57 UTC, nventive-devops commented
The [build 59208](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=59208) found UI Test snapshots differences: `android-28-xamarin`: **0**, `android-28-xamarin-Snap`: **0**, `ios`: **28**, `ios-Snap`: **106**, `macOS-screenshots`: **35**, `skia-gtk-screenshots`: **9**, `skia-wpf-screenshots`: **11**, `wasm`: **25**, `wasm-automated-net7.0-Benchmarks`: **0**, `wasm-automated-net7.0-Default`: **3**, `wasm-automated-net7.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **0** changed over 0

* `android-28-xamarin-Snap`: **0** changed over 0

* `ios`: **28** changed over 293

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `Flyout_ShowAt_Window_Content_UITests_Windows_UI_Xaml_Controls_FlyoutTests_Flyout_ShowAt_Window_Content`
  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Taller_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Taller_Mode-3`
  - `TextBox_AutoGrow_Vertically_Wrapping_Test_Uno_UI_Samples_Content_UITests_TextBoxControl_Input_Multiline_AutoHeight`
  - `TextBox_RoundedCorners_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_RoundedCorners`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-1`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-2`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-1`
  </details>

* `ios-Snap`: **106** changed over 996

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Icons_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Icons`
  - `Border_AutoBorderStretchwithtopmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithtopmargin`
  - `Border_BorderLeftwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderLeftwithmargins`
  - `Border_BorderRightwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderRightwithmargins`
  - `Brushes_UITests_Windows_UI_Xaml_Media_BrushesTests_SolidColorBrush_Color_Changed_UITests_Windows_UI_Xaml_Media_BrushesTests_SolidColorBrush_Color_Changed`
  - `Brushes_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops`
  - `Brushes_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_BitmapIcon_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_BitmapIcon`
  - `Border_AutoBorderStretchwithleftmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithleftmargin`
  - `Border_BorderTopwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderTopwithmargins`
  - `Border_Border_Corner_Overlap_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerOverlap`
  - `Border_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle`
  - `Brushes_ImageBrushAlignmentXY_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushAlignmentXY`
  - `Brushes_ImageBrushWithCompositeTransform_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithCompositeTransform`
  - `Brushes_ImageBrushWithLateSource_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithLateSource`
  - `Brushes_Uno_UI_Samples_UITests_ImageBrushTestControl_DoubleImageBrushInList_Uno_UI_Samples_UITests_ImageBrushTestControl_DoubleImageBrushInList`
  - `ComboBox_ComboBox_Disabled_UITests_Windows_UI_Xaml_Controls_ComboBox_ComboBox_Disabled`
  - `CommandBar_CommandBar_Xaml_Automated_UITests_Shared_Windows_UI_Xaml_Controls_CommandBar_CommandBar_Xaml_Automated`
  - `ContentControl_ContentControl_DefaultText_Uno_UI_Samples_Content_UITests_ContentControlTestsControl_ContentControl_DefaultText`
  - `ContentControl_ContentControl_WithPadding_Uno_UI_Samples_Content_UITests_ContentControlTestsControl_ContentControl_WithPadding`
  </details>

* `macOS-screenshots`: **35** changed over 1069

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Animations-BeginTime_MultipleAnimations.png`
  - `ColorPicker-WinUIColorPickerPage.png`
  - `Focus-GetFocus.png`
  - `Image-Image_Stretch_Alignment_Equal.png`
  - `Image-Image_Stretch_None_ScrollViewer.png`
  - `Info-InfoBarPage.png`
  - `MUX-NavigationViewSelectedItemEdgeCasePage.png`
  - `MUX-NavigationViewTopNavPage.png`
  - `MUX-PaneLayoutTestPage.png`
  - `MUX-PersonPicturePage.png`
  - `MUX-TabViewPage.png`
  - `MUX-WinUIColorPickerPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `PagerControl-PagerControlPage.png`
  - `MediaPlayerElement-Using .flv.png`
  - `MediaPlayerElement-Using .mkv.png`
  - `MediaPlayerElement-Using .mov.png`
  - `MediaPlayerElement-Using .ogg.png`
  - `MUX-NavigationViewAnimationPage.png`
  </details>

* `skia-gtk-screenshots`: **9** changed over 1061

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Automation-AutomationProperties_Name.png`
  - `DragAndDrop-DragDrop_TestPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `MUX-NavigationViewCompactPaneLengthTestPage.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  </details>

* `skia-wpf-screenshots`: **11** changed over 1061

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Automation-AutomationProperties_Name.png`
  - `DragAndDrop-DragDrop_TestPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `Transform-TransformToVisual_Translate2d.png`
  - `WinUI-PipsPagerPage.png`
  - `XAML-SimpleDeferLoadStrategy.png`
  </details>

* `wasm`: **25** changed over 1004

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `MUXControlsTestApp.NavigationViewRS4Page`
  - `MUXControlsTestApp.NavigationViewStretchPage`
  - `MUXControlsTestApp.PersonPicturePage`
  - `MUXControlsTestApp.PipsPagerExamples`
  - `SamplesApp.Samples.NavigationViewSample.NavigationViewSample`
  - `SamplesApp.Samples.Windows_UI_Xaml_Controls.NavigationViewTests.NavigationView_BasicNavigation`
  - `SamplesApp.Wasm.Windows_UI_Xaml_Controls.ListView.ListView_IsSelected`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewHeaderImage`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewLargeHeader`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRingPage`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_CustomSources`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_Features`
  - `UITes [...]

2022-10-20 01:45 UTC, nventive-devops commented
The [build 59208](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=59208) found UI Test snapshots differences: `android-28-xamarin`: **0**, `android-28-xamarin-Snap`: **0**, `ios`: **28**, `ios-Snap`: **106**, `macOS-screenshots`: **35**, `skia-gtk-screenshots`: **9**, `skia-wpf-screenshots`: **11**, `wasm`: **25**, `wasm-automated-net7.0-Benchmarks`: **0**, `wasm-automated-net7.0-Default`: **3**, `wasm-automated-net7.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **0** changed over 0

* `android-28-xamarin-Snap`: **0** changed over 0

* `ios`: **28** changed over 293

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `Flyout_ShowAt_Window_Content_UITests_Windows_UI_Xaml_Controls_FlyoutTests_Flyout_ShowAt_Window_Content`
  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Taller_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Taller_Mode-3`
  - `TextBox_AutoGrow_Vertically_Wrapping_Test_Uno_UI_Samples_Content_UITests_TextBoxControl_Input_Multiline_AutoHeight`
  - `TextBox_RoundedCorners_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_RoundedCorners`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-1`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-2`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-1`
  </details>

* `ios-Snap`: **106** changed over 996

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_BitmapIcon_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_BitmapIcon`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Icons_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Icons`
  - `Border_AutoBorderStretchwithleftmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithleftmargin`
  - `Border_AutoBorderStretchwithtopmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithtopmargin`
  - `Border_BorderLeftwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderLeftwithmargins`
  - `Border_BorderRightwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderRightwithmargins`
  - `Border_BorderTopwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderTopwithmargins`
  - `Border_Border_Corner_Overlap_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerOverlap`
  - `Border_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle`
  - `Brushes_ImageBrushAlignmentXY_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushAlignmentXY`
  - `Brushes_ImageBrushWithCompositeTransform_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithCompositeTransform`
  - `Brushes_ImageBrushWithLateSource_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithLateSource`
  - `Brushes_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats`
  - `Brushes_Uno_UI_Samples_UITests_ImageBrushTestControl_DoubleImageBrushInList_Uno_UI_Samples_UITests_ImageBrushTestControl_DoubleImageBrushInList`
  - `ComboBox_ComboBox_NativePopup_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_NativePopup`
  - `ComboBox_ComboBox_Picker_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_Picker`
  - `Brushes_UITests_Windows_UI_Xaml_Media_BrushesTests_SolidColorBrush_Color_Changed_UITests_Windows_UI_Xaml_Media_BrushesTests_SolidColorBrush_Color_Changed`
  - `Brushes_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops`
  - `ComboBox_ComboBox_Disabled_UITests_Windows_UI_Xaml_Controls_ComboBox_ComboBox_Disabled`
  - `CommandBar_CommandBar_Xaml_Automated_UITests_Shared_Windows_UI_Xaml_Controls_CommandBar_CommandBar_Xaml_Automated`
  </details>

* `macOS-screenshots`: **35** changed over 1069

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Animations-BeginTime_MultipleAnimations.png`
  - `ColorPicker-WinUIColorPickerPage.png`
  - `Focus-GetFocus.png`
  - `Info-InfoBarPage.png`
  - `Image-Image_Stretch_Alignment_Equal.png`
  - `Image-Image_Stretch_None_ScrollViewer.png`
  - `MUX-NavigationViewSelectedItemEdgeCasePage.png`
  - `MUX-NavigationViewTopNavPage.png`
  - `MUX-PaneLayoutTestPage.png`
  - `MUX-PersonPicturePage.png`
  - `MUX-TabViewPage.png`
  - `MUX-WinUIColorPickerPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `PagerControl-PagerControlPage.png`
  - `MediaPlayerElement-Using .flv.png`
  - `MediaPlayerElement-Using .mkv.png`
  - `MediaPlayerElement-Using .mov.png`
  - `MediaPlayerElement-Using .ogg.png`
  - `MUX-NavigationViewAnimationPage.png`
  </details>

* `skia-gtk-screenshots`: **9** changed over 1061

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Automation-AutomationProperties_Name.png`
  - `DragAndDrop-DragDrop_TestPage.png`
  - `MUX-NavigationViewCompactPaneLengthTestPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  </details>

* `skia-wpf-screenshots`: **11** changed over 1061

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Automation-AutomationProperties_Name.png`
  - `DragAndDrop-DragDrop_TestPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `Transform-TransformToVisual_Translate2d.png`
  - `WinUI-PipsPagerPage.png`
  - `XAML-SimpleDeferLoadStrategy.png`
  </details>

* `wasm`: **25** changed over 1004

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `MUXControlsTestApp.NavigationViewStretchPage`
  - `SamplesApp.Samples.Windows_UI_Xaml_Controls.NavigationViewTests.NavigationView_BasicNavigation`
  - `MUXControlsTestApp.NavigationViewRS4Page`
  - `MUXControlsTestApp.PersonPicturePage`
  - `MUXControlsTestApp.PipsPagerExamples`
  - `SamplesApp.Samples.NavigationViewSample.NavigationViewSample`
  - `SamplesApp.Wasm.Windows_UI_Xaml_Controls.ListView.ListView_IsSelected`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewHeaderImage`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewLargeHeader`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRingPage`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_CustomSources`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_Features`
  - `UITests.Microsoft_UI_Xaml_Controls.TabViewTests.TabViewPage`
  - `U [...]

2022-10-20 23:26 UTC, nventive-devops commented
The [build 59368](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=59368) found UI Test snapshots differences: `android-28-xamarin`: **0**, `android-28-xamarin-Snap`: **0**, `ios`: **25**, `ios-Snap`: **85**, `macOS-screenshots`: **40**, `skia-gtk-screenshots`: **10**, `skia-wpf-screenshots`: **10**, `wasm`: **32**, `wasm-automated-net7.0-Benchmarks`: **0**, `wasm-automated-net7.0-Default`: **3**, `wasm-automated-net7.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **0** changed over 0

* `android-28-xamarin-Snap`: **0** changed over 0

* `ios`: **25** changed over 293

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `ListView_ObservableCollection_Creation_Count_Added`
  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `ListView_ObservableCollection_Creation_Count_Added_above`
  - `ListView_ObservableCollection_Creation_Count_Removed_above`
  - `ListView_ObservableCollection_Creation_Count_Scrolled1`
  - `ListView_ObservableCollection_Creation_Count_Scrolled2`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `PasswordBox_RevealInScrollViewer_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-3`
  - `TextBox_RoundedCorners_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_RoundedCorners`
  - `TextBox_UpdatedBinding_On_OneWay_Mode_UITests_Windows_UI_Xaml_Controls_TextBox_TextBox_Bindings`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-1`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-2`
  </details>

* `ios-Snap`: **85** changed over 996

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Animations_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background`
  - `Border_AutoBorderStretchwithtopmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithtopmargin`
  - `Brushes_ImageBrushAlignmentXY_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushAlignmentXY`
  - `Brushes_ImageBrushStretch_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushStretch`
  - `Brushes_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description`
  - `Border_AutoBorderStretchwithleftmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithleftmargin`
  - `Border_Border_Corner_Overlap_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerOverlap`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_DoubleAnimationClipping_SamplesApp_Windows_UI_Xaml_Clipping_DoubleAnimationClipping`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_In_Border_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_In_Border`
  - `ComboBox_ComboBox_SelectedItem_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_SelectedItem`
  - `Default_UITests_Shared_Windows_UI_Xaml_Controls_Canvas_Canvas_With_Outer_Clip_UITests_Shared_Windows_UI_Xaml_Controls_Canvas_Canvas_With_Outer_Clip`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_XamlButtonWithClipping_SamplesApp_Windows_UI_Xaml_Clipping_XamlButtonWithClipping`
  - `Clipping_UITests_Shared_Windows_UI_Xaml_Clipping_ClippingRoundedCorners_UITests_Shared_Windows_UI_Xaml_Clipping_ClippingRoundedCorners`
  - `Clipping_UITests_Shared_Windows_UI_Xaml_Clipping_ClippingToControlBounds_UITests_Shared_Windows_UI_Xaml_Clipping_ClippingToControlBounds`
  - `ComboBox_ComboBox_ItemsSource_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_ItemsSource`
  - `ComboBox_ComboBox_PlaceholderText_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_PlaceholderText`
  - `Default_UITests_Shared_Windows_UI_Xaml_Controls_Popup_Popup_Overlay_On_UITests_Shared_Windows_UI_Xaml_Controls_Popup_Popup_Overlay_On`
  - `Default_UITests_Toolkit_ElevatedView_Corners_UITests_Toolkit_ElevatedView_Corners`
  - `Default_UITests_Toolkit_ElevatedView_Dimensions_UITests_Toolkit_ElevatedView_Dimensions`
  </details>

* `macOS-screenshots`: **40** changed over 1069

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `BreadcrumbBar-BreadcrumbBarPage.png`
  - `Buttons-CheckBox_Button.png`
  - `ColorPicker-WinUIColorPickerPage.png`
  - `Gesture Recognizer-Manipulation_Basics.png`
  - `Gesture Recognizer-Pointer Events test bench.png`
  - `Image-Image_Stretch_Alignment_SizeOnControl.png`
  - `Image-Image_Stretch_None_ScrollViewer.png`
  - `Info-InfoBarPage.png`
  - `ListView-ListViewIncrementalLoading.png`
  - `MediaPlayerElement-Original.png`
  - `MUX-NavigationViewTopNavOnlyPage.png`
  - `MUX-PagerControlPage.png`
  - `MUX-TabViewPage.png`
  - `MUX-WinUIColorPickerPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `MediaPlayerElement-Using .avi.png`
  - `MediaPlayerElement-Using .mkv.png`
  - `MediaPlayerElement-Using .mov.png`
  - `MediaPlayerElement-Using .ogg.png`
  </details>

* `skia-gtk-screenshots`: **10** changed over 1061

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Automation-AutomationProperties_Name.png`
  - `Brushes-Ellipse.png`
  - `Image-UniformToFill100x100.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `Transform-TransformToVisual_Translate2d.png`
  </details>

* `skia-wpf-screenshots`: **10** changed over 1061

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `DragAndDrop-DragDrop_TestPage.png`
  - `Image-Image_Stretch_None.png`
  - `Image-Image_Stretch_None_ScrollViewer.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `WinUI-PipsPagerPage.png`
  </details>

* `wasm`: **32** changed over 1004

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `MUXControlsTestApp.NavigationViewBlankPage1`
  - `MUXControlsTestApp.NavigationViewRS4Page`
  - `SamplesApp.Samples.Windows_UI_Xaml_Controls.NavigationViewTests.NavigationView_BasicNavigation`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewChangeView`
  - `MUXControlsTestApp.NavigationViewMenuItemStretchPage`
  - `MUXControlsTestApp.NavigationViewTopNavOnlyPage`
  - `MUXControlsTestApp.PipsPagerPage`
  - `SamplesApp.Samples.NavigationViewSample.NavigationViewSample`
  - `SamplesApp.Wasm.Windows_UI_Xaml_Controls.ListView.ListView_IsSelected`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewVariableHeightComplexTemplate`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListView_Expandable_Item_Large`
  - `UITests.Microsoft_UI_Xaml_Controls.NavigationViewTests.NavigationViewBasicPage`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.Wi [...]

2022-10-21 16:46 UTC, nventive-devops commented
The [build 59443](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=59443) found UI Test snapshots differences: `android-28-xamarin`: **0**, `android-28-xamarin-Snap`: **0**, `ios`: **39**, `ios-Snap`: **87**, `macOS-screenshots`: **46**, `skia-gtk-screenshots`: **9**, `skia-wpf-screenshots`: **7**, `wasm`: **30**, `wasm-automated-net7.0-Benchmarks`: **0**, `wasm-automated-net7.0-Default`: **7**, `wasm-automated-net7.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **0** changed over 0

* `android-28-xamarin-Snap`: **0** changed over 0

* `ios`: **39** changed over 293

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ContentPresenter_Template_Uno_UI_Samples_Content_UITests_ContentPresenter_ContentPresenter_Template`
  - `Flyout_ShowAt_Window_Content_UITests_Windows_UI_Xaml_Controls_FlyoutTests_Flyout_ShowAt_Window_Content`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-0`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_SizeOnControl_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_SizeOnControl_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Taller_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Wider_Mode-0`
  - `Screenshots_Image_Stretch_Alignment_Wider_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Wider_Mode-2`
  </details>

* `ios-Snap`: **87** changed over 996

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_BitmapIcon_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_BitmapIcon`
  - `Border_AutoBorderStretchwithleftmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithleftmargin`
  - `Border_BorderTopwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderTopwithmargins`
  - `Brushes_ImageBrushWithLateSource_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithLateSource`
  - `Brushes_ImageBrushWithRotateTransform_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithRotateTransform`
  - `Brushes_UITests_Windows_UI_Xaml_Media_BrushesTests_SolidColorBrush_Color_Changed_UITests_Windows_UI_Xaml_Media_BrushesTests_SolidColorBrush_Color_Changed`
  - `Brushes_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Icons_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Icons`
  - `Border_AutoBorderStretchwithtopmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithtopmargin`
  - `Border_BorderLeftwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderLeftwithmargins`
  - `Border_BorderRightwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderRightwithmargins`
  - `Border_Border_Simple_No_Background_With_Content_Border_With_Background_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_No_Background_With_Content_Border_With_Background`
  - `Brushes_ImageBrushWithScaleTransform_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithScaleTransform`
  - `Brushes_Uno_UI_Samples_UITests_ImageBrushTestControl_DoubleImageBrushInList_Uno_UI_Samples_UITests_ImageBrushTestControl_DoubleImageBrushInList`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_ButtonWithClippingAndOffset_SamplesApp_Windows_UI_Xaml_Clipping_ButtonWithClippingAndOffset`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_DoubleAnimationClipping_SamplesApp_Windows_UI_Xaml_Clipping_DoubleAnimationClipping`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_In_Border_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_In_Border`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_in_Canvas_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_in_Canvas`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_ButtonClippingTestsControl_SamplesApp_Windows_UI_Xaml_Clipping_ButtonClippingTestsControl`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_XamlButtonWithClipping_SamplesApp_Windows_UI_Xaml_Clipping_XamlButtonWithClipping`
  </details>

* `macOS-screenshots`: **46** changed over 1069

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Animations-BeginTime_MultipleAnimations.png`
  - `BreadcrumbBar-BreadcrumbBarPage.png`
  - `Brushes-ImageBrush_Stretch_None.png`
  - `ColorPicker-WinUIColorPickerPage.png`
  - `Focus-GetFocus.png`
  - `Image-Image_Fixed_Size_Alignment.png`
  - `Image-Image_Formats.png`
  - `Image-Image_Stretch_None_ScrollViewer.png`
  - `ItemsRepeater-UniformGridLayout_Simple.png`
  - `MediaPlayerElement-Original.png`
  - `ListView-ListView_With_ListViews_Count_Measure.png`
  - `MUX-NavigationViewSelectedItemEdgeCasePage.png`
  - `MUX-NavigationViewTopNavPage.png`
  - `MUX-PagerControlPage.png`
  - `MUX-TabViewPage.png`
  - `MUX-WinUIProgressBarPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `PagerControl-PagerControlPage.png`
  - `MediaPlayerElement-Using .avi.png`
  </details>

* `skia-gtk-screenshots`: **9** changed over 1061

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `DragAndDrop-DragDrop_TestPage.png`
  - `MUX-TabViewPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `TabView-TabViewPage.png`
  </details>

* `skia-wpf-screenshots`: **7** changed over 1061

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Automation-AutomationProperties_Name.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  </details>

* `wasm`: **30** changed over 1004

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `MUXControlsTestApp.PipsPagerPage`
  - `SamplesApp.Samples.NavigationViewSample.NavigationViewSample`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewLargeHeader`
  - `MUXControlsTestApp.NavigationViewBlankPage1`
  - `MUXControlsTestApp.NavigationViewRS4Page`
  - `MUXControlsTestApp.NavigationViewTopNavPage`
  - `SamplesApp.Wasm.Windows_UI_Xaml_Controls.ListView.ListView_IsSelected`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewVariableHeightComplexTemplate`
  - `UITests.Microsoft_UI_Xaml_Controls.ColorPickerTests.ColorPickerSample`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRingPage`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_CustomSources`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_Features`
  - `UITests.Microsoft_UI_Xaml_Controls.TabViewTests.TabViewPage`
  - `UITests.Shared.Microsoft_UI_Xaml_Controls.ColorPickerTests.WinUIColorPickerPage`
  - `UITe [...]

2022-10-22 21:54 UTC, nventive-devops commented
The [build 59583](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=59583) found UI Test snapshots differences: `android-28-xamarin`: **0**, `android-28-xamarin-Snap`: **0**, `ios`: **35**, `ios-Snap`: **96**, `macOS-screenshots`: **31**, `skia-gtk-screenshots`: **9**, `skia-wpf-screenshots`: **12**, `wasm`: **39**, `wasm-automated-net7.0-Benchmarks`: **0**, `wasm-automated-net7.0-Default`: **15**, `wasm-automated-net7.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **0** changed over 0

* `android-28-xamarin-Snap`: **0** changed over 0

* `ios`: **35** changed over 296

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `ListView_ObservableCollection_Creation_Count_Added`
  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `ListView_ObservableCollection_Creation_Count_Added_above`
  - `ListView_ObservableCollection_Creation_Count_Removed_above`
  - `ListView_ObservableCollection_Creation_Count_Scrolled1`
  - `ListView_ObservableCollection_Creation_Count_Scrolled2`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_SizeOnControl_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_SizeOnControl_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Wider_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Wider_Mode-2`
  </details>

* `ios-Snap`: **96** changed over 1002

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description`
  - `Border_AutoBorderStretchwithleftmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithleftmargin`
  - `Border_AutoBorderStretchwithtopmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithtopmargin`
  - `Border_Border_Corner_Overlap_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerOverlap`
  - `Border_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle`
  - `Brushes_ImageBrushStretch_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushStretch`
  - `Buttons_Button_Opacity_Automated_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Button_Opacity_Automated`
  - `ComboBox_ComboBox_NativePopup_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_NativePopup`
  - `ComboBox_ComboBox_Picker_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_Picker`
  - `Brushes_ImageBrushAlignmentXY_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushAlignmentXY`
  - `Brushes_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats`
  - `Buttons_Hyperlink_Disabled_nVentive_Umbrella_Views_UI_Samples_Content_UITests_ButtonTestsControl_Hyperlink_Disabled`
  - `Buttons_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Custom_Button_With_ContentTemplate_And_StackPanel_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Custom_Button_With_ContentTemplate_And_StackPanel`
  - `CommandBar_CommandBar_Xaml_Automated_UITests_Shared_Windows_UI_Xaml_Controls_CommandBar_CommandBar_Xaml_Automated`
  - `Default_Uno_UI_Samples_Content_UITests_WebView_WebView_AnchorNavigation_Uno_UI_Samples_Content_UITests_WebView_WebView_AnchorNavigation`
  - `Flyouts_UITests_Windows_UI_Xaml_Controls_FlyoutTests_Flyout_ShowAt_Window_Content_UITests_Windows_UI_Xaml_Controls_FlyoutTests_Flyout_ShowAt_Window_Content`
  - `Default_UITests_Shared_Windows_UI_Xaml_Controls_Canvas_Canvas_With_Outer_Clip_UITests_Shared_Windows_UI_Xaml_Controls_Canvas_Canvas_With_Outer_Clip`
  - `Default_UITests_Shared_Windows_UI_Xaml_Controls_Popup_Popup_Overlay_On_UITests_Shared_Windows_UI_Xaml_Controls_Popup_Popup_Overlay_On`
  - `Gesture_Recognizer_VisualStates_ComboBoxItem_UITests_Shared_Windows_UI_Input_VisualStatesTests_ComboBoxItem`
  - `Gesture_Recognizer_VisualStates_ListViewItem_UITests_Shared_Windows_UI_Input_VisualStatesTests_ListViewItem`
  </details>

* `macOS-screenshots`: **31** changed over 1075

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ColorPicker-WinUIColorPickerPage.png`
  - `Gesture Recognizer-Pointer Events test bench.png`
  - `Info-InfoBarPage.png`
  - `Image-Image_Stretch_Alignment_SizeOnControl.png`
  - `MUX-NavigationViewPage.png`
  - `MUX-NavigationViewRS4Page.png`
  - `MUX-NavigationViewTopNavPage.png`
  - `MUX-WinUIColorPickerPage.png`
  - `PagerControl-PagerControlPage.png`
  - `MediaPlayerElement-Using .avi.png`
  - `MediaPlayerElement-Using .flv.png`
  - `MediaPlayerElement-Using .ogg.png`
  - `MUX-InfoBarPage.png`
  - `MUX-NavigationViewBasicPage.png`
  - `MUX-NavigationViewCustomThemeResourcesPage.png`
  - `MUX-WinUIProgressBarPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `NavigationView-NavigationViewCompactPaneLengthTestPage.png`
  - `NavigationView-NavigationViewCustomThemeResourcesPage.png`
  </details>

* `skia-gtk-screenshots`: **9** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Brushes-Ellipse.png`
  - `Date Picking-CalendarView_Theming.png`
  - `Image-UniformToFill100x100.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  </details>

* `skia-wpf-screenshots`: **12** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Automation-AutomationProperties_Name.png`
  - `Brushes-Ellipse.png`
  - `Date Picking-CalendarView_Theming.png`
  - `Image-UniformToFill100x100.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `Transform-TransformToVisual_Translate2d.png`
  - `WinUI-PipsPagerExamples.png`
  </details>

* `wasm`: **39** changed over 1010

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `MUXControlsTestApp.NavigationViewMenuItemStretchPage`
  - `MUXControlsTestApp.NavigationViewMinimalPage`
  - `MUXControlsTestApp.PipsPagerPage`
  - `SamplesApp.Samples.Windows_UI_Xaml_Controls.NavigationViewTests.NavigationView_BasicNavigation`
  - `MUXControlsTestApp.NavigationViewAnimationPage`
  - `MUXControlsTestApp.NavigationViewRS4Page`
  - `MUXControlsTestApp.NavigationViewTopNavPage`
  - `SamplesApp.Wasm.Windows_UI_Xaml_Controls.ListView.ListView_IsSelected`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewHeaderImage`
  - `UITests.Microsoft_UI_Xaml_Controls.ColorPickerTests.ColorPickerSample`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRingPage`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_CustomSources`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_Features`
   [...]

2022-10-23 03:58 UTC, nventive-devops commented
The [build 59588](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=59588) found UI Test snapshots differences: `android-28-xamarin`: **0**, `android-28-xamarin-Snap`: **0**, `ios`: **40**, `ios-Snap`: **116**, `macOS-screenshots`: **33**, `skia-gtk-screenshots`: **7**, `skia-wpf-screenshots`: **12**, `wasm`: **46**, `wasm-automated-net7.0-Benchmarks`: **0**, `wasm-automated-net7.0-Default`: **13**, `wasm-automated-net7.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **0** changed over 0

* `android-28-xamarin-Snap`: **0** changed over 0

* `ios`: **40** changed over 296

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `ListView_ObservableCollection_Creation_Count_Added`
  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `ListView_ObservableCollection_Creation_Count_Added_above`
  - `ListView_ObservableCollection_Creation_Count_Removed_above`
  - `ListView_ObservableCollection_Creation_Count_Scrolled1`
  - `ListView_ObservableCollection_Creation_Count_Scrolled2`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Horizontal_Mode-3`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Horizontal_Mode-1`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Horizontal_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-0`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-3`
  </details>

* `ios-Snap`: **116** changed over 1002

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Brushes_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats`
  - `Automation_UITests_Shared_Windows_UI_Xaml_Automation_AutomationProperties_Name_UITests_Shared_Windows_UI_Xaml_Automation_AutomationProperties_Name`
  - `Brushes_ImageBrushAlignmentXY_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushAlignmentXY`
  - `Brushes_ImageBrushStretch_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushStretch`
  - `Buttons_Button_Opacity_Automated_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Button_Opacity_Automated`
  - `Buttons_Hyperlink_Disabled_nVentive_Umbrella_Views_UI_Samples_Content_UITests_ButtonTestsControl_Hyperlink_Disabled`
  - `Buttons_Simple_TextBlockButton_Uno_UI_Samples_Content_UITests_TextBlockControl_Simple_TextBlockButton`
  - `Buttons_ToggleSwitch_IsEnable_Automated_Uno_UI_Samples_Content_UITests_ButtonTestsControl_ToggleSwitch_IsEnable_Automated`
  - `Buttons_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsBasicPage_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsBasicPage`
  - `Buttons_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsFocusPage_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsFocusPage`
  - `ComboBox_ComboBox_ScrollViewer_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_ScrollViewer`
  - `ComboBox_ComboBox_SelectedIndex_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_SelectedIndex`
  - `ComboBox_ComboBox_SelectedItem_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_SelectedItem`
  - `Buttons_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Custom_Button_With_ContentTemplate_And_StackPanel_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Custom_Button_With_ContentTemplate_And_StackPanel`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_XamlButtonWithClipping_SamplesApp_Windows_UI_Xaml_Clipping_XamlButtonWithClipping`
  - `ComboBox_ComboBox_ItemsSource_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_ItemsSource`
  - `ComboBox_ComboBox_MaxDropdownHeight_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_MaxDropdownHeight`
  - `ComboBox_ComboBox_NoDataContext_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_NoDataContext`
  - `ComboBox_ComboBox_Picker_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_Picker`
  - `ComboBox_ComboBox_PlaceholderText_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_PlaceholderText`
  </details>

* `macOS-screenshots`: **33** changed over 1075

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Animations-BeginTime_MultipleAnimations.png`
  - `ColorPicker-WinUIColorPickerPage.png`
  - `Grid-CenteredGridinGridwiththreefixedsizechildren.png`
  - `Image-Image_Stretch_None_ScrollViewer.png`
  - `Info-InfoBarPage.png`
  - `MUX-NavigationViewBasicPage.png`
  - `MUX-NavigationViewCustomThemeResourcesPage.png`
  - `ListView-ListView_With_ListViews_Count_Measure.png`
  - `MediaPlayerElement-Using .avi.png`
  - `MediaPlayerElement-Using .flv.png`
  - `MediaPlayerElement-Using .mkv.png`
  - `MUX-InfoBarPage.png`
  - `NavigationView-NavigationViewTopNavPage.png`
  - `NavigationView-NavigationView_BasicNavigation.png`
  - `MUX-NavigationViewPage.png`
  - `MUX-NavigationViewRS4Page.png`
  - `MUX-NavigationViewTopNavPage.png`
  - `MUX-PagerControlPage.png`
  - `MUX-TabViewPage.png`
  - `MUX-WinUIColorPickerPage.png`
  </details>

* `skia-gtk-screenshots`: **7** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Date Picking-CalendarView_Theming.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  </details>

* `skia-wpf-screenshots`: **12** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Date Picking-CalendarView_Theming.png`
  - `DragAndDrop-DragDrop_TestPage.png`
  - `Image-UniformToFill100x100.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `PipsPager-PipsPagerPage.png`
  - `Transform-TransformToVisual_Translate2d.png`
  - `WinUI-PipsPagerExamples.png`
  </details>

* `wasm`: **46** changed over 1010

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `MUXControlsTestApp.NavigationViewAnimationPage`
  - `MUXControlsTestApp.NavigationViewBlankPage1`
  - `MUXControlsTestApp.NavigationViewMenuItemStretchPage`
  - `MUXControlsTestApp.NavigationViewRS4Page`
  - `MUXControlsTestApp.NavigationViewStretchPage`
  - `MUXControlsTestApp.NavigationViewTopNavOnlyPage`
  - `MUXControlsTestApp.NavigationViewTopNavPage`
  - `MUXControlsTestApp.PipsPagerPage`
  - `SamplesApp.Samples.Windows_UI_Xaml_Controls.NavigationViewTests.NavigationView_BasicNavigation`
  - `SamplesApp.Wasm.Windows_UI_Xaml_Controls.ListView.ListView_IsSelected`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewChangeView`
  - `UITests.Microsoft_UI_Xaml_Controls.ColorPickerTests.ColorPickerSample`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRingPage`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_CustomSources`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_Features`
  - `UITests.Microsoft_UI_Xaml_Controls.TabViewTests.TabViewPage`
  - `UITests.Shared.Microsoft [...]

2022-10-24 01:23 UTC, nventive-devops commented
The [build 59645](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=59645) found UI Test snapshots differences: `android-28-xamarin`: **0**, `android-28-xamarin-Snap`: **0**, `ios`: **34**, `ios-Snap`: **68**, `macOS-screenshots`: **32**, `skia-gtk-screenshots`: **10**, `skia-wpf-screenshots`: **12**, `wasm`: **20**, `wasm-automated-net7.0-Benchmarks`: **0**, `wasm-automated-net7.0-Default`: **5**, `wasm-automated-net7.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **0** changed over 0

* `android-28-xamarin-Snap`: **0** changed over 0

* `ios`: **34** changed over 296

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Flyout_ShowAt_Window_Content_UITests_Windows_UI_Xaml_Controls_FlyoutTests_Flyout_ShowAt_Window_Content`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `ListView_ChangingText_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Changing_Text`
  - `BasicExpressionTest_UITests_Microsoft_UI_Xaml_Controls_NumberBoxTests_NumberBox_ExpressionTest`
  - `ContentPresenter_Template_Uno_UI_Samples_Content_UITests_ContentPresenter_ContentPresenter_Template`
  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `PasswordBox_RevealInScrollViewer_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-0`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Taller_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Taller_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Taller_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Wider_Mode-0`
  </details>

* `ios-Snap`: **68** changed over 1002

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Animations_DoubleAnimation_TranslateX_GenericApp_Views_Content_UITests_Animations_DoubleAnimation_TranslateX`
  - `Animations_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description`
  - `Border_AutoBorderStretchwithleftmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithleftmargin`
  - `Border_AutoBorderStretchwithtopmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithtopmargin`
  - `Border_Border_Corner_Overlap_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerOverlap`
  - `Border_Border_Simple_with_Opacity_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_with_Opacity`
  - `Brushes_ImageBrushAlignmentXY_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushAlignmentXY`
  - `Brushes_ImageBrushStretch_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushStretch`
  - `Border_Uno_UI_Samples_UITests_BorderTestsControl_Border_BorderThickness_Uno_UI_Samples_UITests_BorderTestsControl_Border_BorderThickness`
  - `Brushes_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops`
  - `Brushes_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_XamlButtonWithClipping_SamplesApp_Windows_UI_Xaml_Clipping_XamlButtonWithClipping`
  - `ComboBox_ComboBox_ItemsSource_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_ItemsSource`
  - `ComboBox_ComboBox_MaxDropdownHeight_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_MaxDropdownHeight`
  - `ComboBox_ComboBox_NoDataContext_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_NoDataContext`
  - `ComboBox_ComboBox_Picker_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_Picker`
  - `ComboBox_ComboBox_PlaceholderText_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_PlaceholderText`
  - `ComboBox_ComboBox_SelectedIndex_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_SelectedIndex`
  - `ComboBox_ComboBox_SelectedItem_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_SelectedItem`
  </details>

* `macOS-screenshots`: **32** changed over 1075

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ColorPicker-WinUIColorPickerPage.png`
  - `Image-Image_Fixed_Size_Alignment.png`
  - `Info-InfoBarPage.png`
  - `ListView-ListView_With_ListViews_Count_Measure.png`
  - `MUX-NavigationViewRS4Page.png`
  - `MUX-NavigationViewTopNavPage.png`
  - `MUX-PagerControlPage.png`
  - `MUX-SplitButtonPage.png`
  - `MUX-TabViewPage.png`
  - `MediaPlayerElement-Using .flv.png`
  - `MediaPlayerElement-Using .mov.png`
  - `MUX-HierarchicalNavigationViewMarkup.png`
  - `MUX-InfoBarPage.png`
  - `MUX-NavigationViewCustomThemeResourcesPage.png`
  - `MUX-WinUIColorPickerPage.png`
  - `MUX-WinUIProgressBarPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `NavigationView-NavigationViewCompactPaneLengthTestPage.png`
  - `NavigationView-NavigationViewCustomThemeResourcesPage.png`
  </details>

* `skia-gtk-screenshots`: **10** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `DragAndDrop-DragDrop_TestPage.png`
  - `Date Picking-CalendarView_Theming.png`
  - `Image-UniformToFill100x100.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `WinUI-PipsPagerPage.png`
  </details>

* `skia-wpf-screenshots`: **12** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Brushes-BorderImageBrushRelativeTransform.png`
  - `Brushes-Ellipse.png`
  - `Date Picking-CalendarView_Theming.png`
  - `Image-UniformToFill100x100.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `Transform-TransformToVisual_Translate2d.png`
  - `WinUI-PipsPagerPage.png`
  </details>

* `wasm`: **20** changed over 1010

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `MUXControlsTestApp.NavigationViewTopNavPage`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewChangeView`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewContainerFromItem`
  - `MUXControlsTestApp.NavigationViewMenuItemStretchPage`
  - `MUXControlsTestApp.NavigationViewTopNavOnlyPage`
  - `SamplesApp.Wasm.Windows_UI_Xaml_Controls.ListView.ListView_IsSelected`
  - `SamplesApp.Windows_UI_Xaml_Shapes.StretchPage`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_CustomSources`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_Features`
  - `UITests.Shared.Windows_Devices.Midi.MidiDeviceEnumerationTests`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewVariableHeightComplexTemplate`
  - `UITests.Microsoft_UI_Xaml_Controls.TabViewTes [...]

2022-10-24 05:33 UTC, nventive-devops commented
The [build 59670](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=59670) found UI Test snapshots differences: `android-28-xamarin`: **0**, `android-28-xamarin-Snap`: **0**, `ios`: **36**, `ios-Snap`: **69**, `macOS-screenshots`: **39**, `skia-gtk-screenshots`: **9**, `skia-wpf-screenshots`: **12**, `wasm`: **21**, `wasm-automated-net7.0-Benchmarks`: **0**, `wasm-automated-net7.0-Default`: **9**, `wasm-automated-net7.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **0** changed over 0

* `android-28-xamarin-Snap`: **0** changed over 0

* `ios`: **36** changed over 296

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `BasicExpressionTest_UITests_Microsoft_UI_Xaml_Controls_NumberBoxTests_NumberBox_ExpressionTest`
  - `Flyout_ShowAt_Window_Content_UITests_Windows_UI_Xaml_Controls_FlyoutTests_Flyout_ShowAt_Window_Content`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-1`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-2`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-0`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Taller_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Taller_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Taller_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Wider_Mode-0`
  </details>

* `ios-Snap`: **69** changed over 1002

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Animations_DoubleAnimation_TranslateX_GenericApp_Views_Content_UITests_Animations_DoubleAnimation_TranslateX`
  - `Animations_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background`
  - `Border_AutoBorderStretchwithtopmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithtopmargin`
  - `Border_Border_Simple_with_Opacity_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_with_Opacity`
  - `Border_Uno_UI_Samples_UITests_BorderTestsControl_Border_BorderThickness_Uno_UI_Samples_UITests_BorderTestsControl_Border_BorderThickness`
  - `Brushes_ImageBrushAlignmentXY_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushAlignmentXY`
  - `Brushes_ImageBrushStretch_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushStretch`
  - `Brushes_UITests_Windows_UI_Xaml_Media_BrushesTests_SolidColorBrush_Color_Changed_UITests_Windows_UI_Xaml_Media_BrushesTests_SolidColorBrush_Color_Changed`
  - `Brushes_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description`
  - `Border_AutoBorderStretchwithleftmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithleftmargin`
  - `Border_Border_Corner_Overlap_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerOverlap`
  - `ComboBox_ComboBox_NativePopup_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_NativePopup`
  - `ComboBox_ComboBox_Picker_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_Picker`
  - `Flyouts_UITests_Windows_UI_Xaml_Controls_FlyoutTests_Flyout_ShowAt_Window_Content_UITests_Windows_UI_Xaml_Controls_FlyoutTests_Flyout_ShowAt_Window_Content`
  - `Gesture_Recognizer_UITests_Shared_Windows_UI_Input_GestureRecognizerTests_GestureEventsCommons_UITests_Shared_Windows_UI_Input_GestureRecognizerTests_GestureEventsCommons`
  - `GridView_Uno_UI_Samples_Content_UITests_GridView_GridViewVariableItemHeight_Uno_UI_Samples_Content_UITests_GridView_GridViewVariableItemHeight`
  - `Grid_Grid_with_TextBlock_VerticalAlignment_Uno_UI_Samples_Content_UITests_GridTestsControl_Grid_with_TextBlock_VerticalAlignment`
  - `Grid_Grid_with_Text_HorizontalAlignment_With_Margin_Uno_UI_Samples_Content_UITests_GridTestsControl_Grid_with_Text_HorizontalAlignment_With_Margin`
  - `Grid_Grid_with_UILabel_TextAlignmentVertical_Bottom_Uno_UI_Samples_Content_UITests_GridTestsControl_Grid_with_UILabel_TextAlignmentVertical_Bottom`
  </details>

* `macOS-screenshots`: **39** changed over 1075

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `BreadcrumbBar-BreadcrumbBarPage.png`
  - `Focus-GetFocus.png`
  - `Image-Image_Fixed_Size_Alignment.png`
  - `Image-Image_Formats.png`
  - `Image-SvgImageSource_FromStream.png`
  - `Info-InfoBarPage.png`
  - `Image-Image_Stretch_Alignment_SizeOnControl.png`
  - `Image-Image_Stretch_None_ScrollViewer.png`
  - `ListView-ListView_With_ListViews_Count_Measure.png`
  - `MUX-NavigationViewMinimalPage.png`
  - `MUX-NavigationViewPage.png`
  - `MUX-NavigationViewRS3Page.png`
  - `MUX-NavigationViewRS4Page.png`
  - `MUX-NavigationViewTopNavOnlyPage.png`
  - `MUX-NavigationViewTopNavPage.png`
  - `MUX-PagerControlPage.png`
  - `MUX-TabViewPage.png`
  - `PagerControl-PagerControlPage.png`
  - `MediaPlayerElement-Using .mov.png`
  - `MediaPlayerElement-Using .ogg.png`
  </details>

* `skia-gtk-screenshots`: **9** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Date Picking-CalendarView_Theming.png`
  - `Image-UniformToFill100x100.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `Transform-TransformToVisual_Translate2d.png`
  </details>

* `skia-wpf-screenshots`: **12** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Automation-AutomationProperties_Name.png`
  - `Date Picking-CalendarView_Theming.png`
  - `Image-UniformToFill100x100.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `PipsPager-PipsPagerPage.png`
  - `Transform-TransformToVisual_Translate2d.png`
  - `WinUI-PipsPagerPage.png`
  </details>

* `wasm`: **21** changed over 1010

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `MUXControlsTestApp.NavigationViewMenuItemStretchPage`
  - `MUXControlsTestApp.NavigationViewMinimalPage`
  - `MUXControlsTestApp.RefreshVisualizerPage`
  - `SamplesApp.Wasm.Windows_UI_Xaml_Controls.ListView.ListView_IsSelected`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewContainerFromItem`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewLargeHeader`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListView_Expandable_Item_Large`
  - `UITests.Microsoft_UI_Xaml_Controls.PagerControlTests.PagerControlPage`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_CustomSources`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_Features`
  - `UITests.Microsoft_UI_Xaml_Controls.RatingControlTests.RatingContr [...]

2022-10-24 16:11 UTC, nventive-devops commented
The [build 59722](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=59722) found UI Test snapshots differences: `android-28-xamarin`: **0**, `android-28-xamarin-Snap`: **0**, `ios`: **39**, `ios-Snap`: **99**, `macOS-screenshots`: **34**, `skia-gtk-screenshots`: **11**, `skia-wpf-screenshots`: **9**, `wasm`: **25**, `wasm-automated-net7.0-Benchmarks`: **0**, `wasm-automated-net7.0-Default`: **10**, `wasm-automated-net7.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **0** changed over 0

* `android-28-xamarin-Snap`: **0** changed over 0

* `ios`: **39** changed over 296

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ComboBoxTests_ToggleDisabled_UITests_Windows_UI_Xaml_Controls_ComboBox_ComboBox_ToggleDisabled`
  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `ListView_ObservableCollection_Creation_Count_Added`
  - `ListView_ObservableCollection_Creation_Count_Added_above`
  - `ListView_ObservableCollection_Creation_Count_Removed_above`
  - `ListView_ObservableCollection_Creation_Count_Scrolled1`
  - `ListView_ObservableCollection_Creation_Count_Scrolled2`
  - `ComboBoxTests_ToggleDisabled_ComboBox_Disabled`
  - `ComboBoxTests_ToggleDisabled_ComboBox_Enabled`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Wider_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Wider_Mode-2`
  </details>

* `ios-Snap`: **99** changed over 1002

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description`
  - `Border_AutoBorderStretchwithleftmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithleftmargin`
  - `Border_Border_Corner_Overlap_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerOverlap`
  - `Brushes_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops`
  - `Animations_DoubleAnimation_TranslateX_GenericApp_Views_Content_UITests_Animations_DoubleAnimation_TranslateX`
  - `Animations_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background`
  - `Border_AutoBorderStretchwithtopmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithtopmargin`
  - `Border_Border_Simple_with_Opacity_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_with_Opacity`
  - `Border_Uno_UI_Samples_UITests_BorderTestsControl_Border_BorderThickness_Uno_UI_Samples_UITests_BorderTestsControl_Border_BorderThickness`
  - `Brushes_ImageBrushAlignmentXY_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushAlignmentXY`
  - `Brushes_ImageBrushStretch_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushStretch`
  - `Brushes_Uno_UI_Samples_UITests_ImageBrushTestControl_Ellipse_Uno_UI_Samples_UITests_ImageBrushTestControl_Ellipse`
  - `Buttons_Button_Opacity_Automated_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Button_Opacity_Automated`
  - `Buttons_Hyperlink_Disabled_nVentive_Umbrella_Views_UI_Samples_Content_UITests_ButtonTestsControl_Hyperlink_Disabled`
  - `Buttons_Simple_TextBlockButton_Uno_UI_Samples_Content_UITests_TextBlockControl_Simple_TextBlockButton`
  - `Buttons_ToggleSwitch_IsEnable_Automated_Uno_UI_Samples_Content_UITests_ButtonTestsControl_ToggleSwitch_IsEnable_Automated`
  - `Buttons_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsBasicPage_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsBasicPage`
  - `Buttons_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsFocusPage_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsFocusPage`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_DoubleAnimationClipping_SamplesApp_Windows_UI_Xaml_Clipping_DoubleAnimationClipping`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_In_Border_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_In_Border`
  </details>

* `macOS-screenshots`: **34** changed over 1075

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Gesture Recognizer-Pointer Events test bench.png`
  - `Image-Image_Stretch_Alignment_SizeOnControl.png`
  - `Image-Image_Stretch_None_ScrollViewer.png`
  - `Info-InfoBarPage.png`
  - `MediaPlayerElement-Using .mov.png`
  - `MediaPlayerElement-Using .ogg.png`
  - `MUX-HierarchicalNavigationViewMarkup.png`
  - `ListView-ListView_With_ListViews_Count_Measure.png`
  - `MediaPlayerElement-Using .avi.png`
  - `NavigationView-NavigationViewMinimalPage.png`
  - `NavigationView-NavigationViewPage.png`
  - `NavigationView-NavigationViewRS4Page.png`
  - `NavigationView-NavigationViewSelectedItemEdgeCasePage.png`
  - `NavigationView-NavigationViewTopNavPage.png`
  - `MUX-NavigationViewCustomThemeResourcesPage.png`
  - `MUX-NavigationViewMinimalPage.png`
  - `MUX-NavigationViewPage.png`
  - `MUX-NavigationViewRS3Page.png`
  - `MUX-NavigationViewRS4Page.png`
  - `MUX-NavigationViewTopNavPage.png`
  </details>

* `skia-gtk-screenshots`: **11** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Brushes-DoubleImageBrushInList.png`
  - `Brushes-ImageBrushChangingCornerRadius.png`
  - `Date Picking-CalendarView_Theming.png`
  - `Image-Image_Stretch.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `Transform-TransformToVisual_Translate2d.png`
  </details>

* `skia-wpf-screenshots`: **9** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Date Picking-CalendarView_Theming.png`
  - `Image-UniformToFill100x100.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `Transform-TransformToVisual_Translate2d.png`
  </details>

* `wasm`: **25** changed over 1010

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `MUXControlsTestApp.NavigationViewBlankPage1`
  - `MUXControlsTestApp.NavigationViewRS4Page`
  - `SamplesApp.Wasm.Windows_UI_Xaml_Controls.ListView.ListView_IsSelected`
  - `MUXControlsTestApp.NavigationViewMinimalPage`
  - `MUXControlsTestApp.NavigationViewTopNavOnlyPage`
  - `SamplesApp.Samples.Windows_UI_Xaml_Controls.NavigationViewTests.NavigationView_BasicNavigation`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewContainerFromItem`
  - `UITests.Microsoft_UI_Xaml_Controls.RatingControlTests.RatingControlPage`
  - `UITests.Microsoft_UI_Xaml_Controls.ColorPickerTests.ColorPickerSample`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRingPage`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_CustomSources`
  - `UITests.Microsoft_UI_Xaml_Controls [...]

2022-10-24 20:01 UTC, nventive-devops commented
The [build 59748](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=59748) found UI Test snapshots differences: `android-28-xamarin`: **0**, `android-28-xamarin-Snap`: **0**, `ios`: **29**, `ios-Snap`: **79**, `macOS-screenshots`: **36**, `skia-gtk-screenshots`: **10**, `skia-wpf-screenshots`: **10**, `wasm`: **29**, `wasm-automated-net7.0-Benchmarks`: **0**, `wasm-automated-net7.0-Default`: **9**, `wasm-automated-net7.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **0** changed over 0

* `android-28-xamarin-Snap`: **0** changed over 0

* `ios`: **29** changed over 296

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `ListView_ObservableCollection_Creation_Count_Added`
  - `ListView_ObservableCollection_Creation_Count_Added_above`
  - `ListView_ObservableCollection_Creation_Count_Removed_above`
  - `ListView_ObservableCollection_Creation_Count_Scrolled1`
  - `ListView_ObservableCollection_Creation_Count_Scrolled2`
  - `Flyout_ShowAt_Window_Content_UITests_Windows_UI_Xaml_Controls_FlyoutTests_Flyout_ShowAt_Window_Content`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ScrollViewer_WhenSync_RunNormalAndCompletesWithNonIntermediate_UITests_Shared_Windows_UI_Xaml_Controls_ScrollViewerTests_ScrollViewer_UpdatesMode`
  - `TextBox_UpdatedBinding_On_OneWay_Mode_UITests_Windows_UI_Xaml_Controls_TextBox_TextBox_Bindings`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Horizontal_Mode-1`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Horizontal_Mode-2`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Horizontal_Mode-3`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-1`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-2`
  </details>

* `ios-Snap`: **79** changed over 1002

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Animations_DoubleAnimation_Cumulative_Uno_UI_Samples_Content_UITests_Animations_DoubleAnimation_Cumulative`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description`
  - `Border_AutoBorderStretchwithleftmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithleftmargin`
  - `Animations_DoubleAnimation_TranslateX_GenericApp_Views_Content_UITests_Animations_DoubleAnimation_TranslateX`
  - `Animations_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background`
  - `Border_AutoBorderStretchwithtopmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithtopmargin`
  - `Border_Border_Simple_with_Opacity_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_with_Opacity`
  - `Border_Uno_UI_Samples_UITests_BorderTestsControl_Border_BorderThickness_Uno_UI_Samples_UITests_BorderTestsControl_Border_BorderThickness`
  - `Buttons_Button_Opacity_Automated_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Button_Opacity_Automated`
  - `Buttons_Hyperlink_Disabled_nVentive_Umbrella_Views_UI_Samples_Content_UITests_ButtonTestsControl_Hyperlink_Disabled`
  - `Buttons_Simple_TextBlockButton_Uno_UI_Samples_Content_UITests_TextBlockControl_Simple_TextBlockButton`
  - `Buttons_ToggleSwitch_IsEnable_Automated_Uno_UI_Samples_Content_UITests_ButtonTestsControl_ToggleSwitch_IsEnable_Automated`
  - `Buttons_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsBasicPage_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsBasicPage`
  - `Buttons_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsFocusPage_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsFocusPage`
  - `CommandBar_CommandBar_Xaml_Automated_UITests_Shared_Windows_UI_Xaml_Controls_CommandBar_CommandBar_Xaml_Automated`
  - `Buttons_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Custom_Button_With_ContentTemplate_And_StackPanel_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Custom_Button_With_ContentTemplate_And_StackPanel`
  - `ComboBox_ComboBox_NativePopup_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_NativePopup`
  - `ComboBox_ComboBox_Picker_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_Picker`
  - `Default_UITests_Toolkit_ElevatedView_Corners_UITests_Toolkit_ElevatedView_Corners`
  - `Default_UITests_Toolkit_ElevatedView_Dimensions_UITests_Toolkit_ElevatedView_Dimensions`
  </details>

* `macOS-screenshots`: **36** changed over 1075

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ColorPicker-WinUIColorPickerPage.png`
  - `Gesture Recognizer-Pointer Events test bench.png`
  - `Image-Image_Fixed_Size_Alignment.png`
  - `Image-Image_Stretch_Alignment_SizeOnControl.png`
  - `Image-Image_Stretch_None_ScrollViewer.png`
  - `Info-InfoBarPage.png`
  - `MediaPlayerElement-Using .mov.png`
  - `MediaPlayerElement-Using .ogg.png`
  - `MUX-ColorPickerSample.png`
  - `MUX-HierarchicalNavigationViewMarkup.png`
  - `ListView-ListView_With_ListViews_Count_Measure.png`
  - `MediaPlayerElement-Using .flv.png`
  - `MUX-TabViewPage.png`
  - `MUX-WinUIProgressBarPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `MUX-NavigationViewCustomThemeResourcesPage.png`
  - `MUX-NavigationViewMinimalPage.png`
  - `MUX-NavigationViewPage.png`
  - `MUX-NavigationViewRS4Page.png`
  </details>

* `skia-gtk-screenshots`: **10** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Brushes-EllipsemaskingEllipseSuperpositionPanel.png`
  - `Brushes-Ellipse.png`
  - `Date Picking-CalendarView_Theming.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `Transform-TransformToVisual_Translate2d.png`
  </details>

* `skia-wpf-screenshots`: **10** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Date Picking-CalendarView_Theming.png`
  - `DragAndDrop-DragDrop_TestPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `PipsPager-PipsPagerPage.png`
  - `WinUI-PipsPagerPage.png`
  </details>

* `wasm`: **29** changed over 1010

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `initial_state`
  - `MUXControlsTestApp.NavigationViewAnimationPage`
  - `MUXControlsTestApp.NavigationViewTopNavPage`
  - `SamplesApp.Wasm.Windows_UI_Xaml_Controls.ListView.ListView_IsSelected`
  - `MUXControlsTestApp.NavigationViewMenuItemStretchPage`
  - `MUXControlsTestApp.NavigationViewTopNavOnlyPage`
  - `MUXControlsTestApp.PipsPagerPage`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewContainerFromItem`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewHeaderImage`
  - `UITests.Microsoft_UI_Xaml_Controls.ColorPickerTests.ColorPickerSample`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRingPage`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_CustomSources`
  - `UITests.Microsoft_UI_Xa [...]

2022-10-25 08:59 UTC, nventive-devops commented
The [build 59775](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=59775) found UI Test snapshots differences: `android-28-xamarin`: **0**, `android-28-xamarin-Snap`: **0**, `ios`: **40**, `ios-Snap`: **102**, `macOS-screenshots`: **32**, `skia-gtk-screenshots`: **12**, `skia-wpf-screenshots`: **11**, `wasm`: **30**, `wasm-automated-net7.0-Benchmarks`: **0**, `wasm-automated-net7.0-Default`: **7**, `wasm-automated-net7.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **0** changed over 0

* `android-28-xamarin-Snap`: **0** changed over 0

* `ios`: **40** changed over 296

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `BasicExpressionTest_UITests_Microsoft_UI_Xaml_Controls_NumberBoxTests_NumberBox_ExpressionTest`
  - `ContentPresenter_Template_Uno_UI_Samples_Content_UITests_ContentPresenter_ContentPresenter_Template`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `PasswordBox_RevealInScrollViewer_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Smaller_Mode-3`
  - `TextBox_RoundedCorners_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_RoundedCorners`
  - `TextBox_TextAlignment_Center_Validation_Uno_UI_Samples_Content_UITests_TextBoxControl_TextBox_TextAlignment`
  - `TextBox_TextAlignment_DetectFromContent_Validation_Uno_UI_Samples_Content_UITests_TextBoxControl_TextBox_TextAlignment`
  </details>

* `ios-Snap`: **102** changed over 1002

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Animations_DoubleAnimation_TranslateX_GenericApp_Views_Content_UITests_Animations_DoubleAnimation_TranslateX`
  - `Animations_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background`
  - `Animations_UITests_Windows_UI_Xaml_Media_Animation_FadeInOutThemeAnimationPage_UITests_Windows_UI_Xaml_Media_Animation_FadeInOutThemeAnimationPage`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_BitmapIcon_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_BitmapIcon`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Icons_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Icons`
  - `Border_Border_Simple_with_Opacity_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_with_Opacity`
  - `Border_Uno_UI_Samples_UITests_BorderTestsControl_Border_BorderThickness_Uno_UI_Samples_UITests_BorderTestsControl_Border_BorderThickness`
  - `Brushes_ImageBrushAlignmentXY_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushAlignmentXY`
  - `Brushes_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops`
  - `Brushes_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats`
  - `Buttons_Hyperlink_Disabled_nVentive_Umbrella_Views_UI_Samples_Content_UITests_ButtonTestsControl_Hyperlink_Disabled`
  - `Buttons_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Custom_Button_With_ContentTemplate_And_StackPanel_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Custom_Button_With_ContentTemplate_And_StackPanel`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_ButtonClippingTestsControl_SamplesApp_Windows_UI_Xaml_Clipping_ButtonClippingTestsControl`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_in_Canvas_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_in_Canvas`
  - `Buttons_Button_Opacity_Automated_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Button_Opacity_Automated`
  - `Buttons_Simple_TextBlockButton_Uno_UI_Samples_Content_UITests_TextBlockControl_Simple_TextBlockButton`
  - `Buttons_ToggleSwitch_IsEnable_Automated_Uno_UI_Samples_Content_UITests_ButtonTestsControl_ToggleSwitch_IsEnable_Automated`
  - `Buttons_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsFocusPage_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsFocusPage`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_ButtonWithClippingAndOffset_SamplesApp_Windows_UI_Xaml_Clipping_ButtonWithClippingAndOffset`
  </details>

* `macOS-screenshots`: **32** changed over 1075

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `BreadcrumbBar-BreadcrumbBarPage.png`
  - `Image-SvgImageSource_FromStream.png`
  - `Image-Image_Stretch_Alignment_SizeOnControl.png`
  - `Image-Image_Stretch_Alignment_Wider.png`
  - `Image-Image_Stretch_None_ScrollViewer.png`
  - `ListView-ListView_With_ListViews_Count_Measure.png`
  - `MUX-NavigationViewMinimalPage.png`
  - `MUX-NavigationViewPage.png`
  - `MUX-NavigationViewRS3Page.png`
  - `MUX-NavigationViewRS4Page.png`
  - `MUX-NavigationViewTopNavPage.png`
  - `MUX-TabViewPage.png`
  - `PagerControl-PagerControlPage.png`
  - `MediaPlayerElement-Using .avi.png`
  - `MediaPlayerElement-Using .flv.png`
  - `MediaPlayerElement-Using .ogg.png`
  - `MUX-InfoBarPage.png`
  - `MUX-NavigationViewCustomThemeResourcesPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  </details>

* `skia-gtk-screenshots`: **12** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Brushes-DoubleImageBrushInList.png`
  - `Brushes-Ellipse.png`
  - `Date Picking-CalendarView_Theming.png`
  - `Grid-CenteredGridinGridwiththreefixedsizechildren.png`
  - `MUX-TabViewPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `NavigationView-NavigationViewCompactPaneLengthTestPage.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  </details>

* `skia-wpf-screenshots`: **11** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Automation-AutomationProperties_Name.png`
  - `Brushes-Ellipse.png`
  - `Brushes-ImageBrushChangingCornerRadius.png`
  - `Date Picking-CalendarView_Theming.png`
  - `Image-Image_Stretch.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  </details>

* `wasm`: **30** changed over 1010

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `MUXControlsTestApp.NavigationViewAnimationPage`
  - `MUXControlsTestApp.NavigationViewMenuItemStretchPage`
  - `MUXControlsTestApp.NavigationViewRS4Page`
  - `MUXControlsTestApp.NavigationViewStretchPage`
  - `MUXContr [...]

2022-10-25 18:09 UTC, nventive-devops commented
The [build 59819](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=59819) found UI Test snapshots differences: `android-28-xamarin`: **0**, `android-28-xamarin-Snap`: **0**, `ios`: **31**, `ios-Snap`: **94**, `macOS-screenshots`: **36**, `skia-gtk-screenshots`: **10**, `skia-wpf-screenshots`: **10**, `wasm`: **36**, `wasm-automated-net7.0-Benchmarks`: **0**, `wasm-automated-net7.0-Default`: **10**, `wasm-automated-net7.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **0** changed over 0

* `android-28-xamarin-Snap`: **0** changed over 0

* `ios`: **31** changed over 296

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `BasicExpressionTest_UITests_Microsoft_UI_Xaml_Controls_NumberBoxTests_NumberBox_ExpressionTest`
  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `ListView_ObservableCollection_Creation_Count_Added`
  - `ListView_ObservableCollection_Creation_Count_Added_above`
  - `ListView_ObservableCollection_Creation_Count_Removed_above`
  - `ListView_ObservableCollection_Creation_Count_Scrolled1`
  - `ListView_ObservableCollection_Creation_Count_Scrolled2`
  - `ContentPresenter_Template_Uno_UI_Samples_Content_UITests_ContentPresenter_ContentPresenter_Template`
  - `Flyout_ShowAt_Window_Content_UITests_Windows_UI_Xaml_Controls_FlyoutTests_Flyout_ShowAt_Window_Content`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `PasswordBox_RevealInScrollViewer_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Wider_Mode-1`
  </details>

* `ios-Snap`: **94** changed over 1002

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description`
  - `Border_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle`
  - `Brushes_UITests_Windows_UI_Xaml_Media_BrushesTests_SolidColorBrush_Color_Changed_UITests_Windows_UI_Xaml_Media_BrushesTests_SolidColorBrush_Color_Changed`
  - `Brushes_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops`
  - `Brushes_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats`
  - `Animations_UITests_Windows_UI_Xaml_Media_Animation_FadeInOutThemeAnimationPage_UITests_Windows_UI_Xaml_Media_Animation_FadeInOutThemeAnimationPage`
  - `Brushes_ImageBrushAlignmentXY_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushAlignmentXY`
  - `Brushes_ImageBrushStretch_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushStretch`
  - `Brushes_ImageBrushWithCompositeTransform_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithCompositeTransform`
  - `Brushes_ImageBrushWithRotateTransform_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithRotateTransform`
  - `Brushes_UITests_Shared_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_SameWithDelay_UITests_Shared_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_SameWithDelay`
  - `Brushes_UITests_Windows_UI_Xaml_Media_BrushesTests_Brushes_ImplicitConvert_UITests_Windows_UI_Xaml_Media_BrushesTests_Brushes_ImplicitConvert`
  - `Brushes_Uno_UI_Samples_UITests_ImageBrushTestControl_DoubleImageBrushInList_Uno_UI_Samples_UITests_ImageBrushTestControl_DoubleImageBrushInList`
  - `Buttons_Simple_TextBlockButton_Uno_UI_Samples_Content_UITests_TextBlockControl_Simple_TextBlockButton`
  - `Buttons_ToggleSwitch_IsEnable_Automated_Uno_UI_Samples_Content_UITests_ButtonTestsControl_ToggleSwitch_IsEnable_Automated`
  - `Buttons_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsFocusPage_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsFocusPage`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_DoubleAnimationClipping_SamplesApp_Windows_UI_Xaml_Clipping_DoubleAnimationClipping`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_In_Border_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_In_Border`
  - `ComboBox_ComboBox_SelectedIndex_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_SelectedIndex`
  - `CommandBar_CommandBar_Xaml_Automated_UITests_Shared_Windows_UI_Xaml_Controls_CommandBar_CommandBar_Xaml_Automated`
  </details>

* `macOS-screenshots`: **36** changed over 1075

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Animations-BeginTime_MultipleAnimations.png`
  - `ColorPicker-WinUIColorPickerPage.png`
  - `Info-InfoBarPage.png`
  - `Image-Image_Stretch_Alignment_SizeOnControl.png`
  - `Image-Image_Stretch_None_ScrollViewer.png`
  - `MediaPlayerElement-Using .mkv.png`
  - `MUX-ColorPickerSample.png`
  - `MediaPlayerElement-Using .avi.png`
  - `MediaPlayerElement-Using .flv.png`
  - `MUX-TabViewPage.png`
  - `MUX-WinUIColorPickerPage.png`
  - `MUX-WinUIProgressBarPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `MUX-InfoBarPage.png`
  - `MUX-NavigationViewCompactPaneLengthTestPage.png`
  - `MUX-NavigationViewPage.png`
  - `MUX-NavigationViewRS4Page.png`
  - `MUX-NavigationViewStretchPage.png`
  - `MUX-NavigationViewTopNavPage.png`
  </details>

* `skia-gtk-screenshots`: **10** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Date Picking-CalendarView_Theming.png`
  - `MUX-NavigationViewCompactPaneLengthTestPage.png`
  - `MUX-TabViewPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `PipsPager-PipsPagerPage.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  </details>

* `skia-wpf-screenshots`: **10** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Date Picking-CalendarView_Theming.png`
  - `Image-UniformToFill100x100.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `PipsPager-PipsPagerPage.png`
  - `Transform-TransformToVisual_Translate2d.png`
  </details>

* `wasm`: **36** changed over 1010

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `MUXControlsTestApp.NavigationViewRS4Page`
  - `MUXControlsTestApp.NavigationViewTopNavPage`
  - `SamplesApp.Samples.Windows_UI_Xaml_Controls.NavigationViewTests.NavigationView_BasicNavigation`
  - `SamplesApp.Samples.Windows_UI_Xaml_Controls.NavigationViewTests.NavigationView_Pane_Automated`
  - `SamplesApp.Wasm.Windows_UI_Xaml_Controls.ListView.ListView_IsSelected`
  - `MUXControlsTestApp.NavigationViewMenuItemStretchPage`
  - `MUXControlsTestApp.NavigationViewTopNavOnlyPage`
  - `MUXControlsTestApp.PipsPagerPage`
  - `SamplesApp.Samples.NavigationViewSample.NavigationViewSample` [...]

2022-10-26 00:26 UTC, nventive-devops commented
The [build 59858](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=59858) found UI Test snapshots differences: `android-28-xamarin`: **0**, `android-28-xamarin-Snap`: **0**, `ios`: **34**, `ios-Snap`: **96**, `macOS-screenshots`: **28**, `skia-gtk-screenshots`: **12**, `skia-wpf-screenshots`: **11**, `wasm`: **30**, `wasm-automated-net7.0-Benchmarks`: **0**, `wasm-automated-net7.0-Default`: **6**, `wasm-automated-net7.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **0** changed over 0

* `android-28-xamarin-Snap`: **0** changed over 0

* `ios`: **34** changed over 296

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `ListView_ChangingText_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Changing_Text`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Horizontal_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Smaller_Mode-3`
  - `ListView_ObservableCollection_Creation_Count_Added`
  - `ListView_ObservableCollection_Creation_Count_Added_above`
  - `ListView_ObservableCollection_Creation_Count_Removed_above`
  - `ListView_ObservableCollection_Creation_Count_Scrolled1`
  - `ListView_ObservableCollection_Creation_Count_Scrolled2`
  - `PasswordBox_RevealInScrollViewer_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Horizontal_Mode-1`
  </details>

* `ios-Snap`: **96** changed over 1002

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Animations_UITests_Windows_UI_Xaml_Media_Animation_FadeInOutThemeAnimationPage_UITests_Windows_UI_Xaml_Media_Animation_FadeInOutThemeAnimationPage`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Icons_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Icons`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_BitmapIcon_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_BitmapIcon`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description`
  - `Border_Border_Corner_Overlap_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerOverlap`
  - `Border_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle`
  - `Buttons_Simple_TextBlockButton_Uno_UI_Samples_Content_UITests_TextBlockControl_Simple_TextBlockButton`
  - `Buttons_ToggleSwitch_IsEnable_Automated_Uno_UI_Samples_Content_UITests_ButtonTestsControl_ToggleSwitch_IsEnable_Automated`
  - `Buttons_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsFocusPage_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsFocusPage`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_DoubleAnimationClipping_SamplesApp_Windows_UI_Xaml_Clipping_DoubleAnimationClipping`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_In_Border_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_In_Border`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_in_Canvas_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_in_Canvas`
  - `ComboBox_ComboBox_Disabled_UITests_Windows_UI_Xaml_Controls_ComboBox_ComboBox_Disabled`
  - `ComboBox_ComboBox_ItemDataContext_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_ItemDataContext`
  - `ComboBox_ComboBox_ScrollViewer_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_ScrollViewer`
  - `ComboBox_ComboBox_SelectedIndex_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_SelectedIndex`
  - `ComboBox_ComboBox_SelectedItem_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_SelectedItem`
  - `CommandBar_CommandBar_Xaml_Automated_UITests_Shared_Windows_UI_Xaml_Controls_CommandBar_CommandBar_Xaml_Automated`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_XamlButtonWithClipping_SamplesApp_Windows_UI_Xaml_Clipping_XamlButtonWithClipping`
  - `ComboBox_ComboBox_ItemsSource_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_ItemsSource`
  </details>

* `macOS-screenshots`: **28** changed over 1075

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Animations-BeginTime_MultipleAnimations.png`
  - `Gesture Recognizer-Pointer Events test bench.png`
  - `Image-Image_Fixed_Size_Alignment.png`
  - `Image-Image_Stretch.png`
  - `Image-Image_Stretch_None_ScrollViewer.png`
  - `ListView-ListView_With_ListViews_Count_Measure.png`
  - `MUX-NavigationViewPage.png`
  - `MUX-NavigationViewRS3Page.png`
  - `MUX-NavigationViewRS4Page.png`
  - `MUX-NavigationViewTopNavPage.png`
  - `MUX-TabViewPage.png`
  - `PagerControl-PagerControlPage.png`
  - `MediaPlayerElement-Using .flv.png`
  - `MediaPlayerElement-Using .mkv.png`
  - `MediaPlayerElement-Using .ogg.png`
  - `MUX-InfoBarPage.png`
  - `MUX-WinUIColorPickerPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `NavigationView-NavigationViewCustomThemeResourcesPage.png`
  </details>

* `skia-gtk-screenshots`: **12** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `DragAndDrop-DragDrop_TestPage.png`
  - `Date Picking-CalendarView_Theming.png`
  - `Image-UniformToFill100x100.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `TabView-TabViewPage.png`
  - `Transform-TransformToVisual_Translate2d.png`
  - `WinUI-PipsPagerPage.png`
  </details>

* `skia-wpf-screenshots`: **11** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Date Picking-CalendarView_Theming.png`
  - `Image-UniformToFill100x100.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `PipsPager-PipsPagerExamples.png`
  - `PipsPager-PipsPagerPage.png`
  - `WinUI-PipsPagerPage.png`
  </details>

* `wasm`: **30** changed over 1010

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `MUXControlsTestApp.NavigationViewMinimalPage`
  - `MUXControlsTestApp.NavigationViewTopNavOnlyPage`
  - `MUXControlsTestApp.NavigationViewTopNavPage`
  - `MUXControlsTestApp.PersonPicturePage`
  - `SamplesApp.Samples.Windows_UI_Xaml_Controls.NavigationViewTests.NavigationView_Pane_Automated`
  - `SamplesApp.Wasm.Windows_UI_Xaml_Controls.ListView.ListView_IsSelected`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewChangeView`
  - `UITests.Microsoft_UI_Xaml_Controls.ColorPickerTests.ColorPickerSample`
  - `UITests.Microsoft_UI_Xaml_Controls.PagerControlTests.PagerControlPage`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRingPage`
  -  [...]

2022-10-26 14:12 UTC, spouliot requested changes

2022-10-26 14:16 UTC, dr1rrb approved these changes

2022-10-26 14:20 UTC, jeromelaban commented on build/Uno.WinUI.Svg.nuspec
> +		<file src="..\src\AddIns\Uno.UI.Svg\bin\Uno.UI.Svg.netcoremobile\Release\net6.0-maccatalyst\Uno.UI.Svg.dll" target="lib\net6.0-maccatalyst" />
That would be a question for @MartinZikmund.

2022-10-26 14:21 UTC, jeromelaban commented on build/Uno.WinUI.RemoteControl.nuspec
> +		<dependency id="Newtonsoft.Json" version="12.0.2" />
We'll do an update for all targets in 4.7.

2022-10-26 14:34 UTC, spouliot approved these changes

2022-10-27 00:49 UTC, nventive-devops commented
The [build 60003](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=60003) found UI Test snapshots differences: `android-28-xamarin`: **0**, `android-28-xamarin-Snap`: **0**, `ios`: **38**, `ios-Snap`: **106**, `macOS-screenshots`: **38**, `skia-gtk-screenshots`: **10**, `skia-wpf-screenshots`: **10**, `wasm`: **30**, `wasm-automated-net7.0-Benchmarks`: **0**, `wasm-automated-net7.0-Default`: **5**, `wasm-automated-net7.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **0** changed over 0

* `android-28-xamarin-Snap`: **0** changed over 0

* `ios`: **38** changed over 296

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `ListView_ChangingText_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Changing_Text`
  - `ListView_ObservableCollection_Creation_Count_Added`
  - `ListView_ObservableCollection_Creation_Count_Added_above`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Horizontal_Mode-3`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-1`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Smaller_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Smaller_Mode-2`
  - `ContentPresenter_Template_Uno_UI_Samples_Content_UITests_ContentPresenter_ContentPresenter_Template`
  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `ListView_ObservableCollection_Creation_Count_Removed_above`
  - `ListView_ObservableCollection_Creation_Count_Scrolled1`
  - `ListView_ObservableCollection_Creation_Count_Scrolled2`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-0`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-2`
  </details>

* `ios-Snap`: **106** changed over 1002

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Animations_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background`
  - `Border_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle`
  - `Brushes_UITests_Shared_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_SameWithDelay_UITests_Shared_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_SameWithDelay`
  - `Brushes_UITests_Windows_UI_Xaml_Media_BrushesTests_Brushes_ImplicitConvert_UITests_Windows_UI_Xaml_Media_BrushesTests_Brushes_ImplicitConvert`
  - `Buttons_ToggleSwitch_IsEnable_Automated_Uno_UI_Samples_Content_UITests_ButtonTestsControl_ToggleSwitch_IsEnable_Automated`
  - `Buttons_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsBasicPage_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsBasicPage`
  - `Buttons_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsFocusPage_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsFocusPage`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_In_Border_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_In_Border`
  - `Animations_DoubleAnimation_TranslateX_GenericApp_Views_Content_UITests_Animations_DoubleAnimation_TranslateX`
  - `Border_AutoBorderStretchwithtopmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithtopmargin`
  - `Border_Uno_UI_Samples_UITests_BorderTestsControl_Border_BorderThickness_Uno_UI_Samples_UITests_BorderTestsControl_Border_BorderThickness`
  - `Brushes_ImageBrushAlignmentXY_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushAlignmentXY`
  - `Brushes_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops`
  - `Brushes_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats`
  - `Buttons_Button_Opacity_Automated_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Button_Opacity_Automated`
  - `Buttons_Hyperlink_Disabled_nVentive_Umbrella_Views_UI_Samples_Content_UITests_ButtonTestsControl_Hyperlink_Disabled`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_ButtonClippingTestsControl_SamplesApp_Windows_UI_Xaml_Clipping_ButtonClippingTestsControl`
  - `ComboBox_ComboBox_ScrollViewer_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_ScrollViewer`
  - `ComboBox_ComboBox_SelectedIndex_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_SelectedIndex`
  - `ComboBox_ComboBox_SelectedItem_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_SelectedItem`
  </details>

* `macOS-screenshots`: **38** changed over 1075

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ColorPicker-WinUIColorPickerPage.png`
  - `Gesture Recognizer-Pointer Events test bench.png`
  - `Image-Image_Fixed_Size_Alignment.png`
  - `Grid-CenteredGridinGridwiththreefixedsizechildren.png`
  - `Image-Image_Stretch_None_ScrollViewer.png`
  - `ItemsRepeater-UniformGridLayout_Simple.png`
  - `ListView-ListView_With_ListViews_Count_Measure.png`
  - `MUX-WinUIColorPickerPage.png`
  - `MUX-WinUIProgressBarPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `NavigationView-NavigationViewCompactPaneLengthTestPage.png`
  - `NavigationView-NavigationViewCustomThemeResourcesPage.png`
  - `PagerControl-PagerControlPage.png`
  - `MUX-NavigationViewMenuItemStretchPage.png`
  - `MUX-NavigationViewMinimalPage.png`
  - `MUX-NavigationViewPage.png`
  - `MUX-NavigationViewRS3Page.png`
  - `MUX-NavigationViewRS4Page.png`
  - `MUX-NavigationViewTopNavOnlyPage.png`
  </details>

* `skia-gtk-screenshots`: **10** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Brushes-Ellipse.png`
  - `Image-Image_Stretch.png`
  - `Image-UniformToFill100x100.png`
  - `MUX-NavigationViewCompactPaneLengthTestPage.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  </details>

* `skia-wpf-screenshots`: **10** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Brushes-Ellipse.png`
  - `Automation-AutomationProperties_Name.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `WinUI-PipsPagerPage.png`
  - `XAML-SimpleDeferLoadStrategy.png`
  </details>

* `wasm`: **30** changed over 1010

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `SamplesApp.Samples.NavigationViewSample.NavigationViewSample`
  - `UITests.Microsoft_UI_Xaml_Controls.NavigationViewTests.NavigationViewBasicPage`
  - `MUXControlsTestApp.NavigationViewBlankPage1`
  - `MUXControlsTestApp.NavigationViewMinimalPage`
  - `MUXControlsTestApp.NavigationViewRS4Page`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRingPage`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_CustomSources`
  - `UITests.Microsoft_UI_Xaml_Controls.ProgressRing.WinUIProgressRing_Features`
  - `SamplesApp.Samples.Windows_UI_Xaml_Controls.NavigationViewTests.NavigationView_BasicNavigation`
  - `SamplesApp.Wasm.Windows_UI_Xaml_Controls.ListView.ListView_IsS [...]

2022-10-27 05:32 UTC, nventive-devops commented
The [build 60032](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=60032) found UI Test snapshots differences: `android-28-xamarin`: **0**, `android-28-xamarin-Snap`: **0**, `ios`: **34**, `ios-Snap`: **83**, `macOS-screenshots`: **39**, `skia-gtk-screenshots`: **12**, `skia-wpf-screenshots`: **10**, `wasm`: **36**, `wasm-automated-net7.0-Benchmarks`: **0**, `wasm-automated-net7.0-Default`: **7**, `wasm-automated-net7.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **0** changed over 0

* `android-28-xamarin-Snap`: **0** changed over 0

* `ios`: **34** changed over 296

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `BasicExpressionTest_UITests_Microsoft_UI_Xaml_Controls_NumberBoxTests_NumberBox_ExpressionTest`
  - `Button_Events_UITests_Shared_Windows_UI_Xaml_Controls_Button_Button_Events`
  - `ContentPresenter_Template_Uno_UI_Samples_Content_UITests_ContentPresenter_ContentPresenter_Template`
  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `ListView_ChangingText_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Changing_Text`
  - `ListView_ObservableCollection_Creation_Count_Removed_above`
  - `ListView_ObservableCollection_Creation_Count_Scrolled1`
  - `ListView_ObservableCollection_Creation_Count_Scrolled2`
  - `Screenshots_Image_Stretch_Alignment_SizeOnControl_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_SizeOnControl_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_SizeOnControl_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Smaller_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Smaller_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Smaller_Mode-3`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `ListView_ObservableCollection_Creation_Count_Added`
  - `ListView_ObservableCollection_Creation_Count_Added_above`
  </details>

* `ios-Snap`: **83** changed over 1002

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Border_BorderTopwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderTopwithmargins`
  - `Border_Border_Corner_Overlap_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerOverlap`
  - `Border_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle`
  - `Brushes_UITests_Windows_UI_Xaml_Media_BrushesTests_SolidColorBrush_Color_Changed_UITests_Windows_UI_Xaml_Media_BrushesTests_SolidColorBrush_Color_Changed`
  - `Brushes_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops`
  - `Brushes_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats`
  - `Animations_UITests_Windows_UI_Xaml_Media_Animation_FadeInOutThemeAnimationPage_UITests_Windows_UI_Xaml_Media_Animation_FadeInOutThemeAnimationPage`
  - `Border_BorderLeftwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderLeftwithmargins`
  - `Border_BorderRightwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderRightwithmargins`
  - `Brushes_ImageBrushAlignmentXY_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushAlignmentXY`
  - `Brushes_ImageBrushStretch_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushStretch`
  - `Brushes_ImageBrushWithCompositeTransform_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithCompositeTransform`
  - `Brushes_ImageBrushWithRotateTransform_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithRotateTransform`
  - `Brushes_UITests_Shared_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_SameWithDelay_UITests_Shared_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_SameWithDelay`
  - `Brushes_UITests_Windows_UI_Xaml_Media_BrushesTests_Brushes_ImplicitConvert_UITests_Windows_UI_Xaml_Media_BrushesTests_Brushes_ImplicitConvert`
  - `Brushes_Uno_UI_Samples_UITests_ImageBrushTestControl_DoubleImageBrushInList_Uno_UI_Samples_UITests_ImageBrushTestControl_DoubleImageBrushInList`
  - `Buttons_Hyperlink_CanExecute_False_nVentive_Umbrella_Views_UI_Samples_Content_UITests_ButtonTestsControl_Hyperlink_CanExecute_False`
  - `ComboBox_ComboBox_Disabled_UITests_Windows_UI_Xaml_Controls_ComboBox_ComboBox_Disabled`
  - `ContentControl_ContentControl_WithPadding_Uno_UI_Samples_Content_UITests_ContentControlTestsControl_ContentControl_WithPadding`
  - `Default_UITests_Shared_Windows_UI_Xaml_Controls_Canvas_Canvas_With_Outer_Clip_UITests_Shared_Windows_UI_Xaml_Controls_Canvas_Canvas_With_Outer_Clip`
  </details>

* `macOS-screenshots`: **39** changed over 1075

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `BreadcrumbBar-BreadcrumbBarPage.png`
  - `ColorPicker-WinUIColorPickerPage.png`
  - `CommandBar-Native.png`
  - `Gesture Recognizer-Pointer Events test bench.png`
  - `Grid-CenteredGridinGridwiththreefixedsizechildren.png`
  - `Image-Image_Stretch_Alignment_SizeOnControl.png`
  - `Info-InfoBarPage.png`
  - `Image-SvgImageSource_FromStream.png`
  - `ListView-ListView_With_ListViews_Count_Measure.png`
  - `ListView-ListView_Weird_Measure.png`
  - `MUX-NavigationViewPage.png`
  - `MUX-NavigationViewRS3Page.png`
  - `MUX-NavigationViewRS4Page.png`
  - `MUX-NavigationViewTopNavPage.png`
  - `MUX-PersonPicturePage.png`
  - `MediaPlayerElement-Using .flv.png`
  - `MediaPlayerElement-Using .mkv.png`
  - `MediaPlayerElement-Using .mov.png`
  - `MediaPlayerElement-Using .ogg.png`
  - `MUX-InfoBarPage.png`
  </details>

* `skia-gtk-screenshots`: **12** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Brushes-Ellipse.png`
  - `DragAndDrop-DragDrop_TestPage.png`
  - `Image-UniformToFill100x100.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `MUX-NavigationViewCustomThemeResourcesPage.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `Transform-TransformToVisual_Translate2d.png`
  - `WinUI-PipsPagerPage.png`
  </details>

* `skia-wpf-screenshots`: **10** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Automation-AutomationProperties_Name.png`
  - `DragAndDrop-DragDrop_TestPage.png`
  - `Image-UniformToFill100x100.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `Transform-TransformToVisual_Translate2d.png`
  </details>

* `wasm`: **36** changed over 1010

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `initial_state`
  - `MUXControlsTestApp.NavigationViewAnimationPage`
  - `MUXControlsTestApp.NavigationViewBlankPage1`
  - `MUXControlsTestApp.NavigationViewRS4Page`
  - `MUXControlsTestApp.PipsPagerExamples`
  - `MUXControlsTestApp.PipsPagerPage`
  - `MUXControlsTestApp.RefreshVisualizerPage`
  - `SamplesApp.Wasm.Windows_UI_Xaml_Controls.ListView.ListView_IsSelected`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewChangeView`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewHeaderImage`
  - `UITests.Microsoft_UI_Xaml_Controls.ColorPickerTests.ColorPickerSample`
  - `UITests.Microsoft_UI_Xaml_Controls.NavigationViewTests.NavigationViewBasicPage`
  - `UITests.Microsoft_UI_Xaml_Controls.PagerControlTests.PagerControlPage`
  - `U [...]

2022-10-27 14:02 UTC, nventive-devops commented
The [build 60064](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=60064) found UI Test snapshots differences: `android-28-xamarin`: **0**, `android-28-xamarin-Snap`: **0**, `ios`: **32**, `ios-Snap`: **103**, `macOS-screenshots`: **37**, `skia-gtk-screenshots`: **10**, `skia-wpf-screenshots`: **11**, `wasm`: **35**, `wasm-automated-net7.0-Benchmarks`: **0**, `wasm-automated-net7.0-Default`: **9**, `wasm-automated-net7.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **0** changed over 0

* `android-28-xamarin-Snap`: **0** changed over 0

* `ios`: **32** changed over 296

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `ContentPresenter_Template_Uno_UI_Samples_Content_UITests_ContentPresenter_ContentPresenter_Template`
  - `Flyout_ShowAt_Window_Content_UITests_Windows_UI_Xaml_Controls_FlyoutTests_Flyout_ShowAt_Window_Content`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `ListView_ChangingText_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Changing_Text`
  - `PasswordBox_RevealInScrollViewer_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-0`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Taller_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Taller_Mode-2`
  </details>

* `ios-Snap`: **103** changed over 1002

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Icons_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Icons`
  - `Brushes_ImageBrushStretch_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushStretch`
  - `Brushes_ImageBrushWithCompositeTransform_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithCompositeTransform`
  - `Brushes_ImageBrushWithRotateTransform_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithRotateTransform`
  - `Brushes_UITests_Windows_UI_Xaml_Media_BrushesTests_SolidColorBrush_Color_Changed_UITests_Windows_UI_Xaml_Media_BrushesTests_SolidColorBrush_Color_Changed`
  - `Brushes_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops_UITests_Windows_UI_Xaml_Media_GradientBrushTests_LinearGradientBrush_Change_Stops`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_BitmapIcon_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_BitmapIcon`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description`
  - `Border_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle`
  - `Brushes_UITests_Shared_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_SameWithDelay_UITests_Shared_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_SameWithDelay`
  - `Brushes_UITests_Windows_UI_Xaml_Media_BrushesTests_Brushes_ImplicitConvert_UITests_Windows_UI_Xaml_Media_BrushesTests_Brushes_ImplicitConvert`
  - `Brushes_Uno_UI_Samples_UITests_ImageBrushTestControl_DoubleImageBrushInList_Uno_UI_Samples_UITests_ImageBrushTestControl_DoubleImageBrushInList`
  - `Buttons_Simple_TextBlockButton_Uno_UI_Samples_Content_UITests_TextBlockControl_Simple_TextBlockButton`
  - `Buttons_ToggleSwitch_IsEnable_Automated_Uno_UI_Samples_Content_UITests_ButtonTestsControl_ToggleSwitch_IsEnable_Automated`
  - `Buttons_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsFocusPage_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsFocusPage`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_ButtonWithClippingAndOffset_SamplesApp_Windows_UI_Xaml_Clipping_ButtonWithClippingAndOffset`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_DoubleAnimationClipping_SamplesApp_Windows_UI_Xaml_Clipping_DoubleAnimationClipping`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_In_Border_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_In_Border`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_in_Canvas_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_in_Canvas`
  - `ComboBox_ComboBox_ScrollViewer_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_ScrollViewer`
  </details>

* `macOS-screenshots`: **37** changed over 1075

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Brushes-DynamicBrushes_On_Shapes.png`
  - `Buttons-Custom_Button_With_ContentTemplate.png`
  - `ColorPicker-WinUIColorPickerPage.png`
  - `Gesture Recognizer-Pointer Events test bench.png`
  - `Image-Image_Stretch.png`
  - `Image-Image_Stretch_Alignment_SizeOnControl.png`
  - `Image-Image_Stretch_None_ScrollViewer.png`
  - `Info-InfoBarPage.png`
  - `Image-Image_Formats.png`
  - `Image-SvgImageSource_FromStream.png`
  - `ItemsRepeater-UniformGridLayout_Simple.png`
  - `MUX-NavigationViewPage.png`
  - `MUX-NavigationViewRS4Page.png`
  - `ListView-ListView_With_ListViews_Count_Measure.png`
  - `MediaPlayerElement-Using .flv.png`
  - `MediaPlayerElement-Using .mov.png`
  - `MediaPlayerElement-Using .ogg.png`
  - `MUX-ColorPickerSample.png`
  - `MUX-NavigationViewAnimationPage.png`
  - `MUX-NavigationViewCustomThemeResourcesPage.png`
  </details>

* `skia-gtk-screenshots`: **10** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Brushes-DoubleImageBrushInList.png`
  - `Brushes-Ellipse.png`
  - `ColorPicker-WinUIColorPickerPage.png`
  - `Image-UniformToFill100x100.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  </details>

* `skia-wpf-screenshots`: **11** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Brushes-ImageBrushChangingCornerRadius.png`
  - `Image-Image_Stretch.png`
  - `Image-UniformToFill100x100.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `PipsPager-PipsPagerPage.png`
  - `WinUI-PipsPagerPage.png`
  </details>

* `wasm`: **35** changed over 1010

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `MUXControlsTestApp.NavigationViewAnimationPage`
  - `MUXControlsTestApp.NavigationViewRS4Page`
  - `SamplesApp.Wasm.Windows_UI_Xaml_Controls.ListView.ListView_IsSelected`
  - `MUXControlsTestApp.NavigationViewMenuItemStretchPage`
  - `MUXControlsTestApp.NavigationViewStretchPage`
  - `MUXControlsTestApp.NavigationViewTopNavOnlyPage`
  - `MUXControlsTestApp.PipsPagerPage`
  - `SamplesApp.Samples.Windows_UI_Xaml_Controls.Navi [...]

2022-10-27 17:41 UTC, nventive-devops commented
The [build 60100](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=60100) found UI Test snapshots differences: `android-28-xamarin`: **0**, `android-28-xamarin-Snap`: **0**, `ios`: **37**, `ios-Snap`: **115**, `macOS-screenshots`: **36**, `skia-gtk-screenshots`: **12**, `skia-wpf-screenshots`: **10**, `wasm`: **32**, `wasm-automated-net7.0-Benchmarks`: **0**, `wasm-automated-net7.0-Default`: **7**, `wasm-automated-net7.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **0** changed over 0

* `android-28-xamarin-Snap`: **0** changed over 0

* `ios`: **37** changed over 296

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ContentPresenter_Template_Uno_UI_Samples_Content_UITests_ContentPresenter_ContentPresenter_Template`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `ListView_ObservableCollection_Creation_Count_Removed_above`
  - `ListView_ObservableCollection_Creation_Count_Scrolled1`
  - `ListView_ObservableCollection_Creation_Count_Scrolled2`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-1`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-2`
  - `ListView_ObservableCollection_Creation_Count_Added`
  - `ListView_ObservableCollection_Creation_Count_Added_above`
  - `PasswordBox_RevealInScrollViewer_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-0`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-3`
  </details>

* `ios-Snap`: **115** changed over 1002

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_BitmapIcon_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_BitmapIcon`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description`
  - `Border_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle`
  - `Brushes_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats_UITests_Windows_UI_Xaml_Media_ImageBrushTests_ImageBrush_Formats`
  - `Animations_DoubleAnimation_TranslateX_GenericApp_Views_Content_UITests_Animations_DoubleAnimation_TranslateX`
  - `Animations_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background`
  - `Automation_UITests_Shared_Windows_UI_Xaml_Automation_AutomationProperties_Name_UITests_Shared_Windows_UI_Xaml_Automation_AutomationProperties_Name`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Icons_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Icons`
  - `Border_Border_Simple_with_Opacity_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_with_Opacity`
  - `Border_Uno_UI_Samples_UITests_BorderTestsControl_Border_BorderThickness_Uno_UI_Samples_UITests_BorderTestsControl_Border_BorderThickness`
  - `Brushes_ImageBrushStretch_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushStretch`
  - `Brushes_ImageBrushWithLateSource_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithLateSource`
  - `Brushes_ImageBrushWithRotateTransform_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithRotateTransform`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_ButtonWithClippingAndOffset_SamplesApp_Windows_UI_Xaml_Clipping_ButtonWithClippingAndOffset`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_DoubleAnimationClipping_SamplesApp_Windows_UI_Xaml_Clipping_DoubleAnimationClipping`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_In_Border_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_In_Border`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_in_Canvas_SamplesApp_Windows_UI_Xaml_Clipping_Transform_Ellipse_in_Canvas`
  - `ComboBox_ComboBox_ScrollViewer_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_ScrollViewer`
  - `ComboBox_ComboBox_SelectedItem_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_SelectedItem`
  - `CommandBar_CommandBar_Xaml_Automated_UITests_Shared_Windows_UI_Xaml_Controls_CommandBar_CommandBar_Xaml_Automated`
  </details>

* `macOS-screenshots`: **36** changed over 1075

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Animations-BeginTime_MultipleAnimations.png`
  - `Brushes-DynamicBrushes_On_Shapes.png`
  - `Buttons-Custom_Button_With_ContentTemplate.png`
  - `ColorPicker-WinUIColorPickerPage.png`
  - `Gesture Recognizer-Pointer Events test bench.png`
  - `Image-Image_Fixed_Size_Alignment.png`
  - `Info-InfoBarPage.png`
  - `Image-Image_Stretch.png`
  - `Image-Image_Stretch_Alignment_SizeOnControl.png`
  - `MediaPlayerElement-Using .avi.png`
  - `MediaPlayerElement-Using .mov.png`
  - `MediaPlayerElement-Using .ogg.png`
  - `MUX-NavigationViewAnimationPage.png`
  - `MUX-NavigationViewCustomThemeResourcesPage.png`
  - `MUX-WinUIColorPickerPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `NavigationView-NavigationViewCompactPaneLengthTestPage.png`
  - `NavigationView-NavigationViewCustomThemeResourcesPage.png`
  - `NavigationView-NavigationViewPage.png`
  </details>

* `skia-gtk-screenshots`: **12** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Brushes-Ellipse.png`
  - `DragAndDrop-DragDrop_TestPage.png`
  - `Image-UniformToFill100x100.png`
  - `Image-Image_Formats.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `NavigationView-NavigationViewCustomThemeResourcesPage.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `Transform-TransformToVisual_Translate2d.png`
  </details>

* `skia-wpf-screenshots`: **10** changed over 1067

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Brushes-Ellipse.png`
  - `DragAndDrop-DragDrop_TestPage.png`
  - `MUX-WinUIProgressRingPage.png`
  - `MUX-WinUIProgressRing_CustomSources.png`
  - `Progress-WindowsProgressRing_GH1220.png`
  - `Progress-WinUIProgressRingPage.png`
  - `Progress-WinUIProgressRing_CustomSources.png`
  - `Progress-WinUIProgressRing_Features.png`
  - `PipsPager-PipsPagerPage.png`
  - `WinUI-PipsPagerPage.png`
  </details>

* `wasm`: **32** changed over 1010

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `MUXControlsTestApp.NavigationViewStretchPage`
  - `MUXControlsTestApp.PipsPagerPage`
  - `SamplesApp.Samples.Windows_UI_Xaml_Controls.NavigationViewTests.NavigationView_BasicNavigation`
  - `SamplesApp.Samples.Windows_UI_Xaml_Controls.NavigationViewTests.NavigationView_Pane_Automated`
  - `MUXControlsTestApp.NavigationViewRS4Page`
  - `SamplesApp.Wasm.Windows_UI_Xaml_Controls.ListView.ListView_IsSelected`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewContainerFromItem`
  - `SamplesApp.Windows_UI_Xaml_Controls.ListView.ListViewHeaderImage`
  - `UITests.Mi [...]

2022-10-28 01:04 UTC, merged