Feat:- Remove the Visual Search from WASM
unoplatform/uno pull request #12084
Opened 2023-04-26 14:03 UTC by Darsh0307

GitHub Issue (If applicable): closes #

## PR Type

What kind of change does this PR introduce?

 Code style update (formatting)

## What is the current behavior?

It is showing us a Visual Search in the edge.

## What is the new behavior?

Now there will be no more visual search on the wasm

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

2023-04-26 18:33 UTC, Youssef1313 commented on src/Uno.UI/WasmCSS/Uno.UI.css
> +  pointer-events: none;
This is already applied to `.uno-uielement`:

https://github.com/unoplatform/uno/blob/337801acc17433fb31195ed925ef922a6c16a376/src/Uno.UI/WasmCSS/Uno.UI.css#L28-L35

Shouldn't HtmlImage already be a UIElement and already have `pointer-events: none`? Am I missing anything?

2023-05-11 13:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/unoplatform/uno?pullRequest=12084) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/unoplatform/uno?pullRequest=12084) before we can accept your contribution.<br/>**7** out of **9** committers have signed the CLA.<br/><br/>:white_check_mark: MartinZikmund<br/>:white_check_mark: ajpinedam<br/>:white_check_mark: Youssef1313<br/>:white_check_mark: jeromelaban<br/>:white_check_mark: pictos<br/>:white_check_mark: Xiaoy312<br/>:white_check_mark: dr1rrb<br/>:x: Darsh0307<br/>:x: ci<br/><hr/>**ci** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unoplatform/uno?pullRequest=12084) it.</sub>

2023-05-11 15:21 UTC, MartinZikmund approved these changes

2023-05-11 15:35 UTC, Youssef1313 commented on src/Uno.UI/UI/Xaml/Controls/Image/HtmlImage.wasm.cs
> +		IsHitTestVisible = false;
@dr1rrb Any pointer-related concerns?

2023-05-11 21:23 UTC, nventive-devops commented
The [build 78842](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=78842) found UI Test snapshots differences: `android-28-xamarin`: **42**, `android-28-xamarin-Snap`: **75**, `ios`: **32**, `ios-Snap`: **126**, `macOS-screenshots`: **19**, `skia-gtk-screenshots`: **22**, `skia-wpf-screenshots`: **15**, `wasm`: **43**, `wasm-automated-net7.0-UWP-Benchmarks`: **0**, `wasm-automated-net7.0-UWP-Default`: **11**, `wasm-automated-net7.0-UWP-RuntimeTests`: **0**, `wasm-automated-net7.0-WinUI-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **42** changed over 832

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Affect_Measurement_polygon_PolygonPage_-_ChangeShape-After_clear`
  - `Affect_Measurement_polygon_PolygonPage_-_ClearShape`
  - `Affect_Measurement_polygon_SamplesApp_Windows_UI_Xaml_Shapes_PolygonPage`
  - `BasicNavigationView_SamplesApp_Samples_Windows_UI_Xaml_Controls_NavigationViewTests_NavigationView_Pane_Automated`
  - `Check_ListView_Swallows_Measure_UITests_Shared_Windows_UI_Xaml_Controls_ListView_ListView_With_ListViews_Count_Measure`
  - `CommandTest_UITests_Microsoft_UI_Xaml_Controls_SplitButtonTests_SplitButtonPage`
  - `FocusManager_GetFocusedElement_Border_Validation_Uno_UI_Samples_Content_UITests_FocusTests_FocusManager_GetFocus_Automated`
  - `FocusManager_GetFocusedElement_ListViewItem_Validation_Uno_UI_Samples_Content_UITests_FocusTests_FocusManager_GetFocus_Automated`
  - `FocusManager_GetFocusedElement_ListViewItem_Validation_FocusManager_-_GetFocusedElement_-_ListViewItem_-_1_-_Initial_State`
  - `FocusManager_GetFocusedElement_ListViewItem_Validation_FocusManager_-_GetFocusedElement_-_ListViewItem_-_2_-_After_Selection`
  - `FocusManager_GetFocusedElement_TextBoxSingleLine_LostFocus_Validation_Uno_UI_Samples_Content_UITests_FocusTests_FocusManager_GetFocus_Automated`
  - `FocusManager_GetFocusedElement_TextBoxSingleLine_Validation_FocusManager_-_GetFocusedElement_-_TextBoxSingleLine_-_1_-_Initial_State`
  - `FocusManager_GetFocusedElement_TextBoxSingleLine_Validation_FocusManager_-_GetFocusedElement_-_TextBoxSingleLine_-_2_-_After_Selection`
  - `FocusManager_GetFocusedElement_TextBoxSingleLine_Validation_Uno_UI_Samples_Content_UITests_FocusTests_FocusManager_GetFocus_Automated`
  - `LineSegment_SamplesApp_Windows_UI_Xaml_Media_Geometry_LineSegmentPage`
  - `ListView_ChangeHeight_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListViewChangeHeight`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_Expanded_State`
  - `ListView_ItemClicked_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_ItemClick`
  - `ListView_SelectedItems_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListViewSelectedItems`
  - `Measure_CollapsedShapeInSmallScrollViewer_final`
  </details>

* `android-28-xamarin-Snap`: **75** changed over 1041

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `BreadcrumbBar_MUXControlsTestApp_BreadcrumbBarPage_MUXControlsTestApp_BreadcrumbBarPage`
  - `Brushes_ImageBrushAlignmentXY2_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushAlignmentXY2`
  - `Brushes_ImageBrushAlignmentXY_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushAlignmentXY`
  - `Brushes_ImageBrushStretch2_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushStretch2`
  - `Brushes_ImageBrushStretch_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushStretch`
  - `Buttons_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsPage_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsPage`
  - `Clipping_UITests_Shared_Windows_UI_Xaml_Clipping_ClippingToControlBounds_UITests_Shared_Windows_UI_Xaml_Clipping_ClippingToControlBounds`
  - `ColorPicker_ColorPickerSample_UITests_Microsoft_UI_Xaml_Controls_ColorPickerTests_ColorPickerSample`
  - `CommandBar_Native_Uno_UI_Samples_Content_UITests_CommandBar_CommandBar_Native`
  - `Default_UITests_Toolkit_ElevatedView_Levels_UITests_Toolkit_ElevatedView_Levels`
  - `Expander_WinUIExpanderPage_UITests_Shared_Microsoft_UI_Xaml_Controls_ExpanderTests_WinUIExpanderPage`
  - `Default_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ListView_ListView_IsSelected_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ListView_ListView_IsSelected`
  - `Grid_Grid_with_MinWidth_MinHeight_Uno_UI_Samples_Content_UITests_GridTestsControl_Grid_with_MinWidth_MinHeight`
  - `Image_UITests_Windows_UI_Xaml_Controls_ImageTests_SvgImageSource_Icons_UITests_Windows_UI_Xaml_Controls_ImageTests_SvgImageSource_Icons`
  - `Image_UITests_Windows_UI_Xaml_Controls_ImageTests_SvgImageSource_NoSize_UITests_Windows_UI_Xaml_Controls_ImageTests_SvgImageSource_NoSize`
  - `ItemsRepeater_UITests_Windows_UI_Xaml_Controls_Repeater_StackLayout_Simple_UITests_Windows_UI_Xaml_Controls_Repeater_StackLayout_Simple`
  - `ItemsRepeater_UITests_Windows_UI_Xaml_Controls_Repeater_UniformGridLayout_Simple_UITests_Windows_UI_Xaml_Controls_Repeater_UniformGridLayout_Simple`
  - `ListView_ListViewChangeView_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListViewChangeView`
  - `Image_Image_Stretch_Full_Taller_Uno_UI_Samples_UITests_Image_Image_Stretch_Full_Taller`
  - `Image_UITests_Shared_Windows_UI_Xaml_Controls_ImageTests_Image_Stretch_Algmnt_Inf_Horizontal_UITests_Shared_Windows_UI_Xaml_Controls_ImageTests_Image_Stretch_Algmnt_Inf_Horizontal`
  </details>

* `ios`: **32** changed over 291

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Check_CornerRadius_Border_CornerRadius=5`
  - `Check_CornerRadius_Border_No_CornerRadius`
  - `Check_CornerRadius_Border_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Toggle`
  - `ContentPresenter_Template_Uno_UI_Samples_Content_UITests_ContentPresenter_ContentPresenter_Template`
  - `FlyoutTest_Target_Uno_UI_Samples_Content_UITests_Flyout_Flyout_Target`
  - `Flyout_ShowAt_Window_Content_UITests_Windows_UI_Xaml_Controls_FlyoutTests_Flyout_ShowAt_Window_Content`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Taller_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Taller_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Wider_Mode-0`
  - `Screenshots_Image_Stretch_Alignment_Wider_Mode-1`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Horizontal_Mode-1`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Horizontal_Mode-2`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-1`
  </details>

* `ios-Snap`: **126** changed over 1032

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Reason_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Reason`
  - `Border_AutoBorderStretchwithtopmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithtopmargin`
  - `Border_BorderTopwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderTopwithmargins`
  - `Border_Border_Simple_with_Opacity_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_with_Opacity`
  - `Border_NonUniformThicknessandRadius_Uno_UI_Samples_UITests_BorderTestsControl_NonUniformThicknessandRadius`
  - `Brushes_ImageBrushStretch_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushStretch`
  - `Brushes_UITests_Windows_UI_Xaml_Media_BrushesTests_SolidColorBrush_Color_Changed_UITests_Windows_UI_Xaml_Media_BrushesTests_SolidColorBrush_Color_Changed`
  [...]

2023-05-12 13:49 UTC, Youssef1313 commented on src/Uno.UI/UI/Xaml/Controls/Image/HtmlImage.wasm.cs
> +		IsHitTestVisible = false;
I don't know if we have such a test, but best to have a test for `Tapped` event specifically for `Image`

2023-05-12 15:37 UTC, MartinZikmund commented on src/Uno.UI/UI/Xaml/Controls/Image/HtmlImage.wasm.cs
> +		IsHitTestVisible = false;
I did test the pointer events specifically, but yes, will also verify with a test

2023-05-16 17:47 UTC, dr1rrb commented on src/Uno.UI/UI/Xaml/Controls/Image/HtmlImage.wasm.cs
> +		IsHitTestVisible = false;
Yes I think that this will break the `Tapped` event and all other pointer events, including manipulation events (which is commonly use to zoom on images for instance).

I tried on my computer, setting the `pointer-events: none;` doesn't seems to prevent that menu. I pretty sure that tehre a better way to fix it, for instance I noticed that images in bing.com does not have that menu and pointer events are not disabled. (Removed all layer above the images and still no menu, without having bing in the exemption list of my browser).

BTW changing the `IsHitTestVisible` will impact the "public API" of the image, the `HitTestVisibility = HitTestability.Invisible;` should be sufficient and won't impact application code.

2023-05-16 17:48 UTC, dr1rrb requested changes
This will probably break pointer events, we need to add test for that ... and probably find a better approach.

2023-05-31 12:21 UTC, MartinZikmund commented on src/Uno.UI/UI/Xaml/Controls/Image/HtmlImage.wasm.cs
> +		IsHitTestVisible = false;
@dr1rrb I have tested the `Tapped` event, and having it on `Image` worked (the hit test changes are on `HtmlImage`). Overall though, the menu does not show reliably and it seems the browser has some non-specific exemptions to it. However, using `pointer-events: none` seems to be the only reliable way to hide it always (and that is what people on Stack Overflow ended up with too)

Regarding `IsHitTestVisible` - the change is on `HtmlImage` only, so it shouldn't matter much, no? As this is internal implementation detail of `Image` on WASM anyway?

2025-01-31 11:53 UTC, closed without merging