[wasm]Fix the canvas measure size
unoplatform/uno pull request #5116
Opened 2021-02-03 05:37 UTC by Daoting

GitHub Issue (If applicable): #5115 

## PR Type

What kind of change does this PR introduce?
- Bugfix

## What is the current behavior?

Canvas does not draw internal sub-canvas.

## What is the new behavior?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

2021-02-03 12:29 UTC, jeromelaban commented
@carldebilly

2021-02-03 19:45 UTC, carldebilly requested changes
Needs change

2021-02-03 19:45 UTC, carldebilly commented on src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.Layout.cs
> +			return new Size(maxWidth, maxHeight);
I just checked the source code of UWP/WinUI for the `<Canvas>` control (something I can't share here for obvious reasons) and the results on Windows is a constant `0, 0`.

So this fix is not appropriate and could break existing applications. Another fix should be found for #5115.

2022-02-23 12:50 UTC, MartinZikmund commented
I think this PR is no longer relevant, as the underlying problem is now fixed.

2022-02-23 12:50 UTC, closed without merging