Dev/djo/docs full text search
unoplatform/uno pull request #5687
Opened 2021-04-06 12:10 UTC by nv-jbleau

GitHub Issue (If applicable): #

## PR Type

What kind of change does this PR introduce?

## What is the current behavior?

## What is the new behavior?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

2021-04-06 12:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/unoplatform/uno?pullRequest=5687) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/unoplatform/uno?pullRequest=5687) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: nv-jbleau<br/>:white_check_mark: davidjohnoliver<br/>:x: nv-ksavaria<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unoplatform/uno?pullRequest=5687) it.</sub>

2021-04-06 12:14 UTC, nv-jbleau commented
before: 
![before](https://user-images.githubusercontent.com/62605510/113709105-1bd0a080-96b0-11eb-8774-d50fdfcc618b.PNG)
and after 
![after](https://user-images.githubusercontent.com/62605510/113709134-212deb00-96b0-11eb-8431-c57faccc3de6.PNG)

2021-04-06 14:18 UTC, nventive-devops commented
The [build 27027](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=27027) found UI Test snapshots differences: `android-28`: **28**, `android-28-Snap`: **364**, `ios`: **25**, `ios-Snap`: **36**, `skia-gtk-screenshots`: **35**, `wasm`: **10**, `wasm-automated-net5.0-Default`: **2**, `wasm-automated-net5.0-RuntimeTests`: **0**, `wasm-automated-netstandard2.0-Benchmarks`: **0**, `wasm-automated-netstandard2.0-Default`: **4**, `wasm-automated-netstandard2.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28`: **28** changed over 683

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ComboBoxTests_Fullscreen_Popup_Generic_Closed`
  - `ComboBoxTests_Fullscreen_Popup_Generic_Opened`
  - `CommandBar_LongTitle_Validation_CommandBar_-_LongTitle_-_3_-_Orientation_Portrait`
  - `CommandBar_LongTitle_Validation_CommandBar_-_LongTitle_-_4_-_Orientation_Landscape`
  - `CommandTest_UITests_Microsoft_UI_Xaml_Controls_SplitButtonTests_SplitButtonPage`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_3_-_Remove_Focus_on_disabledTextBox`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_3_-_Remove_Focus_on_disabledTextBox`
  - `ListView_ListViewVariableItemHeightLong_InitializesTest_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListViewVariableItemHeightLong`
  - `PasswordBox_AutoGrow_Horizontally_Test_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Simple`
  - `PopupWithOverlay_After`
  - `PopupWithOverlay_UITests_Shared_Windows_UI_Xaml_Controls_Popup_Popup_Overlay_On`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ScrollViewer_Removed_And_Added_Initial-Scrolled`
  - `SequentialAnimations_SamplesApp_Windows_UI_Xaml_Media_Animation_SequentialAnimationsPage`
  - `TextBox_BeforeTextChanging_Validation_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_BeforeTextChanging`
  - `TextBox_DeleteButton_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_DeleteButton_Automated`
  </details>

* `android-28-Snap`: **364** changed over 869

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Button_Custom_Button_With_ContentTemplate_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Custom_Button_With_ContentTemplate`
  - `ComboBox_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_DropDownPlacement_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_DropDownPlacement`
  - `Default_UITests_Windows_UI_Xaml_Controls_DatePicker_DatePicker_Features_UITests_Windows_UI_Xaml_Controls_DatePicker_DatePicker_Features`
  - `Image_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Formats_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Formats`
  - `NavigationView_FluentStyle_NavigationViewSample_SamplesApp_Samples_Microsoft_UI_Xaml_Controls_NavigationViewTests_FluentStyle_FluentStyle_NavigationViewSample`
  - `NavigationView_MUXControlsTestApp_NavigationViewPage_MUXControlsTestApp_NavigationViewPage`
  - `NavigationView_MUXControlsTestApp_NavigationViewRS3Page_MUXControlsTestApp_NavigationViewRS3Page`
  - `NavigationView_MUXControlsTestApp_NavigationViewRS4Page_MUXControlsTestApp_NavigationViewRS4Page`
  - `NavigationView_MUXControlsTestApp_NavigationViewTopNavOnlyPage_MUXControlsTestApp_NavigationViewTopNavOnlyPage`
  - `NavigationView_MUXControlsTestApp_NavigationViewTopNavOverflowButtonPage_MUXControlsTestApp_NavigationViewTopNavOverflowButtonPage`
  - `NavigationView_MUXControlsTestApp_NavigationViewTopNavPage_MUXControlsTestApp_NavigationViewTopNavPage`
  - `NavigationView_MUXControlsTestApp_PaneLayoutTestPage_MUXControlsTestApp_PaneLayoutTestPage`
  - `NavigationView_NavigationViewSample_SamplesApp_Samples_NavigationViewSample_NavigationViewSample`
  - `NavigationView_NavigationView_BasicNavigation_SamplesApp_Samples_Windows_UI_Xaml_Controls_NavigationViewTests_NavigationView_BasicNavigation`
  - `NavigationView_NavigationView_TopNavigation_UITests_Shared_Windows_UI_Xaml_Controls_NavigationViewTests_NavigationView_TopNavigation`
  - `NavigationView_SamplesApp_Samples_Windows_UI_Xaml_Controls_NavigationViewTests_NavigationView_Pane_Automated_SamplesApp_Samples_Windows_UI_Xaml_Controls_NavigationViewTests_NavigationView_Pane_Automated`
  - `NavigationView_UITests_Microsoft_UI_Xaml_Controls_NavigationViewTests_NavigationViewBasicPage_UITests_Microsoft_UI_Xaml_Controls_NavigationViewTests_NavigationViewBasicPage`
  - `NumberBox_MUX_Test_UITests_Shared_Microsoft_UI_Xaml_Controls_NumberBoxTests_MUX_Test`
  - `NumberBox_UITests_Microsoft_UI_Xaml_Controls_NumberBoxTests_NumberBox_ExpressionTest_UITests_Microsoft_UI_Xaml_Controls_NumberBoxTests_NumberBox_ExpressionTest`
  - `NumberBox_UITests_Microsoft_UI_Xaml_Controls_NumberBoxTests_NumberBox_Header_UITests_Microsoft_UI_Xaml_Controls_NumberBoxTests_NumberBox_Header`
  </details>

* `ios`: **25** changed over 263

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Keyboard_Textbox_InsideScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `Large_Image_With_Margin_Ready`
  - `Large_Image_With_Margin_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Margin_Large`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_Collapsed_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_Expanded_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_Initial_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Expandable_Item_Large`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithSingleItem_Validation_Collapsed_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithSingleItem_Validation_Expanded_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithSingleItem_Validation_Initial_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithSingleItem_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Expandable_Item_Large`
  - `ListView_ExpandableItemLarge_ExpandHeader_Validation_Collapsed_State`
  - `ListView_ExpandableItemLarge_ExpandHeader_Validation_Expanded_State`
  - `ListView_ExpandableItemLarge_ExpandHeader_Validation_Initial_State`
  - `ListView_ExpandableItemLarge_ExpandHeader_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Expandable_Item_Large`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  </details>

* `ios-Snap`: **36** changed over 861

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ComboBox_ComboBox_NativePopup_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_NativePopup`
  - `ComboBox_ComboBox_Picker_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_Picker`
  - `CommandBar_CommandBar_Background_UITests_Windows_UI_Xaml_Controls_CommandBar_Background_CommandBar_Background_Frame`
  - `ContentControlTestsControl_ContentControl_Nested_TemplatedParent_Uno_UI_Samples_Content_UITests_ContentControlTestsControl_ContentControl_Nested_TemplatedParent`
  - `ContentControlTestsControl_ContentControl_SetNull_Uno_UI_Samples_Content_UITests_ContentControlTestsCont [...]

2021-04-06 14:49 UTC, nv-ksavaria requested changes

2021-04-06 14:49 UTC, nv-ksavaria commented on doc/templates/uno/styles/docfx.js
> +          // if the target of the click isn't the container nor a descendant of the container
Indentation semble différente des lignes du dessus

2021-04-06 14:49 UTC, nv-ksavaria commented on doc/templates/uno/styles/docfx.js
> +
Enlever whitespace

2021-04-06 14:49 UTC, nv-ksavaria commented on doc/templates/uno/styles/scss/main.scss
> +
Enlever whitespace

2021-04-06 14:49 UTC, nv-ksavaria commented on doc/templates/uno/styles/scss/main.scss
> +
Enlever whitespace

2021-04-06 14:49 UTC, nv-ksavaria commented on doc/templates/uno/styles/scss/main.scss
> +      p {
Ajouter un linebreak avant le p

2021-04-06 14:49 UTC, nv-ksavaria commented on doc/templates/uno/toc.html.tmpl
> +      <form role="search" id="search" >
Revoir indentation

2021-04-06 14:49 UTC, nv-ksavaria commented on doc/templates/uno/toc.html.tmpl
> +      <form role="search" id="search" >
Enlever whitespace

2021-04-06 15:05 UTC, nventive-devops commented
The [build 27027](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=27027) found UI Test snapshots differences: `android-28`: **28**, `android-28-Snap`: **364**, `ios`: **25**, `ios-Snap`: **36**, `skia-gtk-screenshots`: **35**, `wasm`: **10**, `wasm-automated-net5.0-Default`: **2**, `wasm-automated-net5.0-RuntimeTests`: **0**, `wasm-automated-netstandard2.0-Benchmarks`: **0**, `wasm-automated-netstandard2.0-Default`: **4**, `wasm-automated-netstandard2.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28`: **28** changed over 683

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ComboBoxTests_Fullscreen_Popup_Generic_Closed`
  - `ComboBoxTests_Fullscreen_Popup_Generic_Opened`
  - `CommandBar_LongTitle_Validation_CommandBar_-_LongTitle_-_3_-_Orientation_Portrait`
  - `CommandBar_LongTitle_Validation_CommandBar_-_LongTitle_-_4_-_Orientation_Landscape`
  - `CommandTest_UITests_Microsoft_UI_Xaml_Controls_SplitButtonTests_SplitButtonPage`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_3_-_Remove_Focus_on_disabledTextBox`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_3_-_Remove_Focus_on_disabledTextBox`
  - `ListView_ListViewVariableItemHeightLong_InitializesTest_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListViewVariableItemHeightLong`
  - `PasswordBox_AutoGrow_Horizontally_Test_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Simple`
  - `PopupWithOverlay_After`
  - `PopupWithOverlay_UITests_Shared_Windows_UI_Xaml_Controls_Popup_Popup_Overlay_On`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ScrollViewer_Removed_And_Added_Initial-Scrolled`
  - `SequentialAnimations_SamplesApp_Windows_UI_Xaml_Media_Animation_SequentialAnimationsPage`
  - `TextBox_BeforeTextChanging_Validation_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_BeforeTextChanging`
  - `TextBox_DeleteButton_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_DeleteButton_Automated`
  </details>

* `android-28-Snap`: **364** changed over 869

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Button_Custom_Button_With_ContentTemplate_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Custom_Button_With_ContentTemplate`
  - `ComboBox_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_DropDownPlacement_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_DropDownPlacement`
  - `Default_UITests_Windows_UI_Xaml_Controls_DatePicker_DatePicker_Features_UITests_Windows_UI_Xaml_Controls_DatePicker_DatePicker_Features`
  - `Image_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Formats_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Formats`
  - `NavigationView_FluentStyle_NavigationViewSample_SamplesApp_Samples_Microsoft_UI_Xaml_Controls_NavigationViewTests_FluentStyle_FluentStyle_NavigationViewSample`
  - `NavigationView_MUXControlsTestApp_NavigationViewPage_MUXControlsTestApp_NavigationViewPage`
  - `NavigationView_MUXControlsTestApp_NavigationViewRS3Page_MUXControlsTestApp_NavigationViewRS3Page`
  - `NavigationView_MUXControlsTestApp_NavigationViewRS4Page_MUXControlsTestApp_NavigationViewRS4Page`
  - `NavigationView_MUXControlsTestApp_NavigationViewTopNavOnlyPage_MUXControlsTestApp_NavigationViewTopNavOnlyPage`
  - `NavigationView_MUXControlsTestApp_NavigationViewTopNavOverflowButtonPage_MUXControlsTestApp_NavigationViewTopNavOverflowButtonPage`
  - `NavigationView_MUXControlsTestApp_NavigationViewTopNavPage_MUXControlsTestApp_NavigationViewTopNavPage`
  - `NavigationView_MUXControlsTestApp_PaneLayoutTestPage_MUXControlsTestApp_PaneLayoutTestPage`
  - `NavigationView_NavigationViewSample_SamplesApp_Samples_NavigationViewSample_NavigationViewSample`
  - `NavigationView_NavigationView_BasicNavigation_SamplesApp_Samples_Windows_UI_Xaml_Controls_NavigationViewTests_NavigationView_BasicNavigation`
  - `NavigationView_NavigationView_TopNavigation_UITests_Shared_Windows_UI_Xaml_Controls_NavigationViewTests_NavigationView_TopNavigation`
  - `NavigationView_SamplesApp_Samples_Windows_UI_Xaml_Controls_NavigationViewTests_NavigationView_Pane_Automated_SamplesApp_Samples_Windows_UI_Xaml_Controls_NavigationViewTests_NavigationView_Pane_Automated`
  - `NavigationView_UITests_Microsoft_UI_Xaml_Controls_NavigationViewTests_NavigationViewBasicPage_UITests_Microsoft_UI_Xaml_Controls_NavigationViewTests_NavigationViewBasicPage`
  - `NumberBox_MUX_Test_UITests_Shared_Microsoft_UI_Xaml_Controls_NumberBoxTests_MUX_Test`
  - `NumberBox_UITests_Microsoft_UI_Xaml_Controls_NumberBoxTests_NumberBox_ExpressionTest_UITests_Microsoft_UI_Xaml_Controls_NumberBoxTests_NumberBox_ExpressionTest`
  - `NumberBox_UITests_Microsoft_UI_Xaml_Controls_NumberBoxTests_NumberBox_Header_UITests_Microsoft_UI_Xaml_Controls_NumberBoxTests_NumberBox_Header`
  </details>

* `ios`: **25** changed over 263

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Keyboard_Textbox_InsideScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `Large_Image_With_Margin_Ready`
  - `Large_Image_With_Margin_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Margin_Large`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_Collapsed_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_Expanded_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_Initial_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Expandable_Item_Large`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithSingleItem_Validation_Collapsed_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithSingleItem_Validation_Expanded_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithSingleItem_Validation_Initial_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithSingleItem_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Expandable_Item_Large`
  - `ListView_ExpandableItemLarge_ExpandHeader_Validation_Collapsed_State`
  - `ListView_ExpandableItemLarge_ExpandHeader_Validation_Expanded_State`
  - `ListView_ExpandableItemLarge_ExpandHeader_Validation_Initial_State`
  - `ListView_ExpandableItemLarge_ExpandHeader_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Expandable_Item_Large`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  </details>

* `ios-Snap`: **36** changed over 861

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ComboBox_ComboBox_NativePopup_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_NativePopup`
  - `ComboBox_ComboBox_Picker_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_Picker`
  - `CommandBar_CommandBar_Background_UITests_Windows_UI_Xaml_Controls_CommandBar_Background_CommandBar_Background_Frame`
  - `ContentControlTestsControl_ContentControl_Nested_TemplatedParent_Uno_UI_Samples_Content_UITests_ContentControlTestsControl_ContentControl_Nested_TemplatedParent`
  - `ContentControlTestsControl_ContentControl_SetNull_Uno_UI_Samples_Content_UITests_ContentControlTestsCont [...]

2021-04-06 17:33 UTC, davidjohnoliver approved these changes

2021-04-06 18:27 UTC, nventive-devops commented
The [build 27037](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=27037) found UI Test snapshots differences: `android-28`: **26**, `android-28-Snap`: **20**, `ios`: **17**, `ios-Snap`: **37**, `skia-gtk-screenshots`: **31**, `wasm`: **10**, `wasm-automated-net5.0-Default`: **1**, `wasm-automated-net5.0-RuntimeTests`: **0**, `wasm-automated-netstandard2.0-Benchmarks`: **0**, `wasm-automated-netstandard2.0-Default`: **2**, `wasm-automated-netstandard2.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28`: **26** changed over 683

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Check_ListView_Swallows_Measure_UITests_Shared_Windows_UI_Xaml_Controls_ListView_ListView_With_ListViews_Count_Measure`
  - `ComboBoxTests_Fullscreen_Popup_Generic_Closed`
  - `ComboBoxTests_Fullscreen_Popup_Generic_Opened`
  - `CommandBar_LongTitle_Validation_CommandBar_-_LongTitle_-_4_-_Orientation_Landscape`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_3_-_Remove_Focus_on_disabledTextBox`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_3_-_Remove_Focus_on_disabledTextBox`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_Expanded_State`
  - `ListView_ListViewVariableItemHeightLong_InitializesTest_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListViewVariableItemHeightLong`
  - `PasswordBox_AutoGrow_Horizontally_Test_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Simple`
  - `PopupWithOverlay_After`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ScrollViewer_Removed_And_Added_Initial-Scrolled`
  - `SequentialAnimations_SamplesApp_Windows_UI_Xaml_Media_Animation_SequentialAnimationsPage`
  - `TextBox_CharacterCasingNormal_ShouldAcceptAllCasing_Test_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_CharacterCasing`
  - `TextBox_MaxLength_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_MaxLength`
  </details>

* `android-28-Snap`: **20** changed over 869

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Button_Custom_Button_With_ContentTemplate_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Custom_Button_With_ContentTemplate`
  - `ComboBox_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_DropDownPlacement_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_DropDownPlacement`
  - `Default_UITests_Windows_UI_Xaml_DragAndDrop_DragDrop_TestPage_UITests_Windows_UI_Xaml_DragAndDrop_DragDrop_TestPage`
  - `Image_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Formats_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Formats`
  - `NavigationView_MUXControlsTestApp_NavigationViewPage_MUXControlsTestApp_NavigationViewPage`
  - `Progress_UITests_Microsoft_UI_Xaml_Controls_ProgressBar_WinUIProgressBarSimple_UITests_Microsoft_UI_Xaml_Controls_ProgressBar_WinUIProgressBarSimple`
  - `Progress_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRingPage_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRingPage`
  - `Progress_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRing_CustomSources_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRing_CustomSources`
  - `Progress_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `TabView_UITests_Microsoft_UI_Xaml_Controls_TabViewTests_TabViewPage_UITests_Microsoft_UI_Xaml_Controls_TabViewTests_TabViewPage`
  - `Transform_Border_With_RotateTransform_SamplesApp_Wasm_Windows_UI_Xaml_Media_Transform_Border_With_RotateTransform`
  - `Transform_Image_With_RotateTransform_Uno_UI_Samples_Content_UITests_Transform_Image_With_RotateTransform`
  - `UIElement_TransformToVisual_Simple_UITests_Shared_Windows_UI_Xaml_UIElementTests_TransformToVisual_Simple`
  - `TextBox_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll`
  - `TextBox_Uno_UI_Samples_UITests_TextBoxControl_TextBox_IsReadOnly_Uno_UI_Samples_UITests_TextBoxControl_TextBox_IsReadOnly`
  - `TimePicker_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_Header_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_Header`
  - `Time_Picker_TimePicker_TimePickerFlyoutStyle_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_TimePickerFlyoutStyle`
  - `UIElement_UITests_Windows_UI_Xaml_UIElementTests_UIElement_InitializationSequence_UITests_Windows_UI_Xaml_UIElementTests_UIElement_InitializationSequence`
  - `WebView_WebView_WithHeaders_Uno_UI_Samples_Content_UITests_WebView_WebView_WithHeaders`
  - `XBind_Phase_Large_Uno_UI_Samples_Content_UITests_XBind_PhaseBinding_Large`
  </details>

* `ios`: **17** changed over 263

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Keyboard_Textbox_InsideScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_Expanded_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_Initial_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Expandable_Item_Large`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithSingleItem_Validation_Collapsed_State`
  - `ListView_ExpandableItemLarge_ExpandHeader_Validation_Expanded_State`
  - `ListView_ExpandableItemLarge_ExpandHeader_Validation_Initial_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_Collapsed_State`
  - `ListView_ExpandableItemLarge_ExpandHeader_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Expandable_Item_Large`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithSingleItem_Validation_Expanded_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithSingleItem_Validation_Initial_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithSingleItem_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Expandable_Item_Large`
  - `ListView_ExpandableItemLarge_ExpandHeader_Validation_Collapsed_State`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `SequentialAnimations_SamplesApp_Windows_UI_Xaml_Media_Animation_SequentialAnimationsPage`
  </details>

* `ios-Snap`: **37** changed over 861

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ComboBox_ComboBox_NativePopup_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_NativePopup`
  - `ComboBox_ComboBox_Picker_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_Picker`
  - `CommandBar_CommandBar_Background_UITests_Windows_UI_Xaml_Controls_CommandBar_Background_CommandBar_Background_Frame`
  - `ContentControlTestsControl_ContentControl_Nested_TemplatedParent_Uno_UI_Samples_Content_UITests_ContentControlTestsControl_ContentControl_Nested_TemplatedParent`
  - `ContentControlTestsControl_ContentControl_SetNull_Uno_UI_Samples_Content_UITests_ContentControlTestsControl_ContentControl_SetNull`
  - `GridTestsControl_Grid_with_Stack_Panel_and_Trimming_Uno_UI_Samples_Content_UITests_GridTestsControl_Grid_with_Stack_Panel_and_Trimming`
  - `ImageBrushTes [...]

2021-04-06 20:33 UTC, nventive-devops commented
The [build 27037](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=27037) found UI Test snapshots differences: `android-28`: **23**, `android-28-Snap`: **21**, `ios`: **6**, `ios-Snap`: **43**, `skia-gtk-screenshots`: **46**, `wasm`: **8**, `wasm-automated-net5.0-Default`: **2**, `wasm-automated-net5.0-RuntimeTests`: **0**, `wasm-automated-netstandard2.0-Benchmarks`: **0**, `wasm-automated-netstandard2.0-Default`: **4**, `wasm-automated-netstandard2.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28`: **23** changed over 683

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ComboBoxTests_Fullscreen_Popup_Generic_Closed`
  - `ComboBoxTests_Fullscreen_Popup_Generic_Opened`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_3_-_Remove_Focus_on_disabledTextBox`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_Expanded_State`
  - `Check_ListView_Swallows_Measure_UITests_Shared_Windows_UI_Xaml_Controls_ListView_ListView_With_ListViews_Count_Measure`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `CommandTest_UITests_Microsoft_UI_Xaml_Controls_SplitButtonTests_SplitButtonPage`
  - `PasswordBox_AutoGrow_Horizontally_Test_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Simple`
  - `PopupWithOverlay_After`
  - `TextBox_CharacterCasingNormal_ShouldAcceptAllCasing_Test_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_CharacterCasing`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ScrollViewer_Removed_And_Added_Initial-Scrolled`
  - `TimePicker_Header_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_Header`
  - `SequentialAnimations_SamplesApp_Windows_UI_Xaml_Media_Animation_SequentialAnimationsPage`
  - `TextBox_MaxLength_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_MaxLength`
  - `TextBox_PageLoadedTest_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_TextChanged`
  - `WebView_NavigateToLongString_AfterSuccess`
  - `When_Basic_UITests_Shared_Windows_UI_Input_GestureRecognizerTests_HoldingTests`
  </details>

* `android-28-Snap`: **21** changed over 869

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ComboBox_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_DropDownPlacement_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_DropDownPlacement`
  - `Default_UITests_Windows_UI_Xaml_DragAndDrop_DragDrop_TestPage_UITests_Windows_UI_Xaml_DragAndDrop_DragDrop_TestPage`
  - `ColorPicker_ColorPickerSample_UITests_Microsoft_UI_Xaml_Controls_ColorPickerTests_ColorPickerSample`
  - `Image_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Formats_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Formats`
  - `Image_UniformToFill100x100_Uno_UI_Samples_UITests_ImageTestsControl_UniformToFill100x100`
  - `NavigationView_MUXControlsTestApp_NavigationViewPage_MUXControlsTestApp_NavigationViewPage`
  - `NavigationView_MUXControlsTestApp_NavigationViewRS4Page_MUXControlsTestApp_NavigationViewRS4Page`
  - `Progress_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Map_MapControl_Uno_UI_Samples_Content_UITests_MapControl_MapControl`
  - `Progress_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRingPage_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRingPage`
  - `Progress_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRing_CustomSources_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRing_CustomSources`
  - `TabView_UITests_Microsoft_UI_Xaml_Controls_TabViewTests_TabViewPage_UITests_Microsoft_UI_Xaml_Controls_TabViewTests_TabViewPage`
  - `NavigationView_MUXControlsTestApp_NavigationViewCustomThemeResourcesPage_MUXControlsTestApp_NavigationViewCustomThemeResourcesPage`
  - `ScrollViewer_UITests_Windows_UI_Xaml_Controls_ScrollViewerTests_ScrollViewer_Padding_UITests_Windows_UI_Xaml_Controls_ScrollViewerTests_ScrollViewer_Padding`
  - `Transform_Image_With_RotateTransform_Uno_UI_Samples_Content_UITests_Transform_Image_With_RotateTransform`
  - `UIElement_TransformToVisual_Simple_UITests_Shared_Windows_UI_Xaml_UIElementTests_TransformToVisual_Simple`
  - `WebView_WebView_WithHeaders_Uno_UI_Samples_Content_UITests_WebView_WebView_WithHeaders`
  - `TextBox_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll`
  - `TimePicker_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_Header_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_Header`
  - `Time_Picker_TimePicker_TimePickerFlyoutStyle_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_TimePickerFlyoutStyle`
  </details>

* `ios`: **6** changed over 263

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `NativeCommandBar_Size_thirdOrientation`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  </details>

* `ios-Snap`: **43** changed over 861

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Border_Border_Simple_No_Background_With_TextBox_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_No_Background_With_TextBox`
  - `ComboBox_ComboBox_NativePopup_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_NativePopup`
  - `Animations_DoubleAnimationUsingKeyFrames_TranslateX_GenericApp_Views_Content_UITests_Animations_DoubleAnimationUsingKeyFrames_TranslateX`
  - `CommandBar_CommandBar_Background_UITests_Windows_UI_Xaml_Controls_CommandBar_Background_CommandBar_Background_Frame`
  - `ContentControlTestsControl_ContentControl_SetNull_Uno_UI_Samples_Content_UITests_ContentControlTestsControl_ContentControl_SetNull`
  - `ContentControlTestsControl_ContentControl_Nested_TemplatedParent_Uno_UI_Samples_Content_UITests_ContentControlTestsControl_ContentControl_Nested_TemplatedParent`
  - `Default_UITests_Windows_UI_Xaml_Controls_ListView_ListViewTemplateRootIsContainer_UITests_Windows_UI_Xaml_Controls_ListView_ListViewTemplateRootIsContainer`
  - `ImageBrushTestControl_ImageBrushWithRotateTransform_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithRotateTransform`
  - `ImageBrushTestControl_ImageBrushAlignmentXY_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushAlignmentXY`
  - `Image_Uno_UI_Samples_UITests_ImageTestsControl_ImageUniformWithinScrollViewer_Uno_UI_Samples_UITests_ImageTestsControl_ImageUniformWithinScrollViewer`
  - `Image_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Margin_Large_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Margin_Large`
  - `ListView_ListViewEmptyGroups_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListViewEmptyGroups`
  - `ListView_ListViewGroupedEmpty_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListViewGroupedEmpty`
  - `ListView_ListViewGroupedVariableHeightComplexTemplate_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListViewGroupedVariableHeightComplexTemplate`
  - `ListView_ListViewHeaderImage_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListViewHeaderImage`
  - `ListView_ListView_Expandable_Item_Large_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Expandable_Item_Large`
  - `Map_MapControl_Uno_UI_Samples_Content_UITests_ [...]

2021-04-06 21:06 UTC, nventive-devops commented
The [build 27037](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=27037) found UI Test snapshots differences: `android-28`: **23**, `android-28-Snap`: **21**, `ios`: **6**, `ios-Snap`: **43**, `skia-gtk-screenshots`: **46**, `wasm`: **8**, `wasm-automated-net5.0-Default`: **2**, `wasm-automated-net5.0-RuntimeTests`: **0**, `wasm-automated-netstandard2.0-Benchmarks`: **0**, `wasm-automated-netstandard2.0-Default`: **4**, `wasm-automated-netstandard2.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28`: **23** changed over 683

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Check_ListView_Swallows_Measure_UITests_Shared_Windows_UI_Xaml_Controls_ListView_ListView_With_ListViews_Count_Measure`
  - `ComboBoxTests_Fullscreen_Popup_Generic_Closed`
  - `ComboBoxTests_Fullscreen_Popup_Generic_Opened`
  - `CommandTest_UITests_Microsoft_UI_Xaml_Controls_SplitButtonTests_SplitButtonPage`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_3_-_Remove_Focus_on_disabledTextBox`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_Expanded_State`
  - `PasswordBox_AutoGrow_Horizontally_Test_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Simple`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `PopupWithOverlay_After`
  - `ScrollViewer_Removed_And_Added_Initial-Scrolled`
  - `SequentialAnimations_SamplesApp_Windows_UI_Xaml_Media_Animation_SequentialAnimationsPage`
  - `TextBox_PageLoadedTest_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_TextChanged`
  - `TextBox_CharacterCasingNormal_ShouldAcceptAllCasing_Test_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_CharacterCasing`
  - `When_Basic_UITests_Shared_Windows_UI_Input_GestureRecognizerTests_HoldingTests`
  - `TextBox_MaxLength_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_MaxLength`
  - `TimePicker_Header_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_Header`
  - `ToggleSwitch_HeaderTest_UITests_Shared_Windows_UI_Xaml_Controls_ToggleSwitchControl_ToggleSwitch_Header`
  </details>

* `android-28-Snap`: **21** changed over 869

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ColorPicker_ColorPickerSample_UITests_Microsoft_UI_Xaml_Controls_ColorPickerTests_ColorPickerSample`
  - `ComboBox_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_DropDownPlacement_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_DropDownPlacement`
  - `Default_UITests_Windows_UI_Xaml_DragAndDrop_DragDrop_TestPage_UITests_Windows_UI_Xaml_DragAndDrop_DragDrop_TestPage`
  - `Image_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Formats_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Formats`
  - `Image_UniformToFill100x100_Uno_UI_Samples_UITests_ImageTestsControl_UniformToFill100x100`
  - `Map_MapControl_Uno_UI_Samples_Content_UITests_MapControl_MapControl`
  - `NavigationView_MUXControlsTestApp_NavigationViewCustomThemeResourcesPage_MUXControlsTestApp_NavigationViewCustomThemeResourcesPage`
  - `NavigationView_MUXControlsTestApp_NavigationViewPage_MUXControlsTestApp_NavigationViewPage`
  - `NavigationView_MUXControlsTestApp_NavigationViewRS4Page_MUXControlsTestApp_NavigationViewRS4Page`
  - `ScrollViewer_UITests_Windows_UI_Xaml_Controls_ScrollViewerTests_ScrollViewer_Padding_UITests_Windows_UI_Xaml_Controls_ScrollViewerTests_ScrollViewer_Padding`
  - `Progress_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRingPage_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRingPage`
  - `Progress_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRing_CustomSources_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRing_CustomSources`
  - `Progress_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `TabView_UITests_Microsoft_UI_Xaml_Controls_TabViewTests_TabViewPage_UITests_Microsoft_UI_Xaml_Controls_TabViewTests_TabViewPage`
  - `TextBox_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll`
  - `TimePicker_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_Header_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_Header`
  - `Time_Picker_TimePicker_TimePickerFlyoutStyle_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_TimePickerFlyoutStyle`
  - `UIElement_UITests_Windows_UI_Xaml_UIElementTests_UIElement_InitializationSequence_UITests_Windows_UI_Xaml_UIElementTests_UIElement_InitializationSequence`
  - `WebView_WebView_WithHeaders_Uno_UI_Samples_Content_UITests_WebView_WebView_WithHeaders`
  - `Transform_Image_With_RotateTransform_Uno_UI_Samples_Content_UITests_Transform_Image_With_RotateTransform`
  </details>

* `ios`: **6** changed over 263

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Keyboard_Textbox_InsideScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `NativeCommandBar_Size_thirdOrientation`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  </details>

* `ios-Snap`: **43** changed over 861

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Animations_DoubleAnimationUsingKeyFrames_TranslateX_GenericApp_Views_Content_UITests_Animations_DoubleAnimationUsingKeyFrames_TranslateX`
  - `Border_Border_Simple_No_Background_With_TextBox_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_No_Background_With_TextBox`
  - `CommandBar_CommandBar_Background_UITests_Windows_UI_Xaml_Controls_CommandBar_Background_CommandBar_Background_Frame`
  - `ComboBox_ComboBox_NativePopup_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_NativePopup`
  - `ContentControlTestsControl_ContentControl_Nested_TemplatedParent_Uno_UI_Samples_Content_UITests_ContentControlTestsControl_ContentControl_Nested_TemplatedParent`
  - `ContentControlTestsControl_ContentControl_SetNull_Uno_UI_Samples_Content_UITests_ContentControlTestsControl_ContentControl_SetNull`
  - `Default_UITests_Windows_UI_Xaml_Controls_ListView_ListViewTemplateRootIsContainer_UITests_Windows_UI_Xaml_Controls_ListView_ListViewTemplateRootIsContainer`
  - `ImageBrushTestControl_ImageBrushAlignmentXY_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushAlignmentXY`
  - `ImageBrushTestControl_ImageBrushWithRotateTransform_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithRotateTransform`
  - `Image_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Margin_Large_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Margin_Large`
  - `Image_Uno_UI_Samples_UITests_ImageTestsControl_ImageUniformWithinScrollViewer_Uno_UI_Samples_UITests_ImageTestsControl_ImageUniformWithinScrollViewer`
  - `Image_ImageSourceUrlMsAppxScheme_Uno_UI_Samples_UITests_ImageTests_ImageSourceUrlMsAppxScheme`
  - `ListView_ListViewEmptyGroups_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListViewEmptyGroups`
  - `Image_Uno_UI_Samples_UITests_Image_Image_Stretch_Alignment_Taller_Uno_UI_Samples_UITests_Image_Image_Stretch_Alignment_Taller`
  - `Image_Uno_UI_Samples_UITests_Image_Image_Stretch_Uno_UI_Samples_UITests_Image_Image_Stretch`
  - `ListView_ListView_Expandable_Item_Large_SamplesApp_Windows_UI_Xaml_Controls_List [...]

2021-04-06 22:11 UTC, nventive-devops commented
The [build 27037](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=27037) found UI Test snapshots differences: `android-28`: **23**, `android-28-Snap`: **21**, `ios`: **6**, `ios-Snap`: **43**, `skia-gtk-screenshots`: **46**, `wasm`: **8**, `wasm-automated-net5.0-Default`: **2**, `wasm-automated-net5.0-RuntimeTests`: **0**, `wasm-automated-netstandard2.0-Benchmarks`: **0**, `wasm-automated-netstandard2.0-Default`: **4**, `wasm-automated-netstandard2.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28`: **23** changed over 683

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ComboBoxTests_Fullscreen_Popup_Generic_Closed`
  - `ComboBoxTests_Fullscreen_Popup_Generic_Opened`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_3_-_Remove_Focus_on_disabledTextBox`
  - `Check_ListView_Swallows_Measure_UITests_Shared_Windows_UI_Xaml_Controls_ListView_ListView_With_ListViews_Count_Measure`
  - `CommandTest_UITests_Microsoft_UI_Xaml_Controls_SplitButtonTests_SplitButtonPage`
  - `PopupWithOverlay_After`
  - `Keyboard_Textbox_InsideScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `SequentialAnimations_SamplesApp_Windows_UI_Xaml_Media_Animation_SequentialAnimationsPage`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_Expanded_State`
  - `TextBox_PageLoadedTest_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_TextChanged`
  - `PasswordBox_AutoGrow_Horizontally_Test_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Simple`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `WebView_NavigateToLongString_AfterSuccess`
  - `ScrollViewer_Removed_And_Added_Initial-Scrolled`
  - `TextBox_CharacterCasingNormal_ShouldAcceptAllCasing_Test_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_CharacterCasing`
  - `TextBox_MaxLength_UITests_Shared_Windows_UI_Xaml_Controls_TextBoxTests_TextBox_MaxLength`
  - `TimePicker_Header_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_Header`
  - `ToggleSwitch_HeaderTest_UITests_Shared_Windows_UI_Xaml_Controls_ToggleSwitchControl_ToggleSwitch_Header`
  </details>

* `android-28-Snap`: **21** changed over 869

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ColorPicker_ColorPickerSample_UITests_Microsoft_UI_Xaml_Controls_ColorPickerTests_ColorPickerSample`
  - `ComboBox_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_DropDownPlacement_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_DropDownPlacement`
  - `Default_UITests_Windows_UI_Xaml_DragAndDrop_DragDrop_TestPage_UITests_Windows_UI_Xaml_DragAndDrop_DragDrop_TestPage`
  - `Image_UniformToFill100x100_Uno_UI_Samples_UITests_ImageTestsControl_UniformToFill100x100`
  - `Image_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Formats_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Formats`
  - `NavigationView_MUXControlsTestApp_NavigationViewCustomThemeResourcesPage_MUXControlsTestApp_NavigationViewCustomThemeResourcesPage`
  - `NavigationView_MUXControlsTestApp_NavigationViewPage_MUXControlsTestApp_NavigationViewPage`
  - `NavigationView_MUXControlsTestApp_NavigationViewRS4Page_MUXControlsTestApp_NavigationViewRS4Page`
  - `Map_MapControl_Uno_UI_Samples_Content_UITests_MapControl_MapControl`
  - `Progress_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRingPage_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRingPage`
  - `Progress_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRing_CustomSources_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRing_CustomSources`
  - `Progress_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `TabView_UITests_Microsoft_UI_Xaml_Controls_TabViewTests_TabViewPage_UITests_Microsoft_UI_Xaml_Controls_TabViewTests_TabViewPage`
  - `ScrollViewer_UITests_Windows_UI_Xaml_Controls_ScrollViewerTests_ScrollViewer_Padding_UITests_Windows_UI_Xaml_Controls_ScrollViewerTests_ScrollViewer_Padding`
  - `Transform_Image_With_RotateTransform_Uno_UI_Samples_Content_UITests_Transform_Image_With_RotateTransform`
  - `UIElement_TransformToVisual_Simple_UITests_Shared_Windows_UI_Xaml_UIElementTests_TransformToVisual_Simple`
  - `TextBox_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll`
  - `TimePicker_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_Header_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_Header`
  - `Time_Picker_TimePicker_TimePickerFlyoutStyle_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_TimePickerFlyoutStyle`
  - `UIElement_UITests_Windows_UI_Xaml_UIElementTests_UIElement_InitializationSequence_UITests_Windows_UI_Xaml_UIElementTests_UIElement_InitializationSequence`
  </details>

* `ios`: **6** changed over 263

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Keyboard_Textbox_InsideScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `NativeCommandBar_Size_thirdOrientation`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  </details>

* `ios-Snap`: **43** changed over 861

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Animations_DoubleAnimationUsingKeyFrames_TranslateX_GenericApp_Views_Content_UITests_Animations_DoubleAnimationUsingKeyFrames_TranslateX`
  - `Border_Border_Simple_No_Background_With_TextBox_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_No_Background_With_TextBox`
  - `ComboBox_ComboBox_NativePopup_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_NativePopup`
  - `CommandBar_CommandBar_Background_UITests_Windows_UI_Xaml_Controls_CommandBar_Background_CommandBar_Background_Frame`
  - `ContentControlTestsControl_ContentControl_Nested_TemplatedParent_Uno_UI_Samples_Content_UITests_ContentControlTestsControl_ContentControl_Nested_TemplatedParent`
  - `ContentControlTestsControl_ContentControl_SetNull_Uno_UI_Samples_Content_UITests_ContentControlTestsControl_ContentControl_SetNull`
  - `Default_UITests_Windows_UI_Xaml_Controls_ListView_ListViewTemplateRootIsContainer_UITests_Windows_UI_Xaml_Controls_ListView_ListViewTemplateRootIsContainer`
  - `ImageBrushTestControl_ImageBrushAlignmentXY_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushAlignmentXY`
  - `ImageBrushTestControl_ImageBrushWithRotateTransform_Uno_UI_Samples_UITests_ImageBrushTestControl_ImageBrushWithRotateTransform`
  - `Image_ImageSourceUrlMsAppxScheme_Uno_UI_Samples_UITests_ImageTests_ImageSourceUrlMsAppxScheme`
  - `Image_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Margin_Large_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Margin_Large`
  - `Image_Uno_UI_Samples_UITests_ImageTestsControl_ImageUniformWithinScrollViewer_Uno_UI_Samples_UITests_ImageTestsControl_ImageUniformWithinScrollViewer`
  - `Image_Uno_UI_Samples_UITests_Image_Image_Stretch_Alignment_Taller_Uno_UI_Samples_UITests_Image_Image_Stretch_Alignment_Taller`
  - `Image_Uno_UI_Samples_UITests_Image_Image_Stretch_Uno_UI_Samples_UITests_Image_Image_Stretch`
  - `ListView_ListViewEmptyGroups_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListViewEmptyGroups`
  - `ListView_ListViewGroupedEmpty_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListViewGroupedEmpty`
  [...]

2021-04-07 09:48 UTC, davidjohnoliver commented
> [![CLA assistant check](https://camo.githubusercontent.com/4c970efeed75dd01f6778bf7e33dec85e4171375cb69acb0927bfc9d437d78d9/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/unoplatform/uno?pullRequest=5687)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/unoplatform/uno?pullRequest=5687) before we can accept your contribution.
> **2** out of **3** committers have signed the CLA.
> 
> ✅ nv-jbleau
> ✅ davidjohnoliver
> ❌ nv-ksavaria
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unoplatform/uno?pullRequest=5687) it.

@nv-ksavaria It's complaining that you haven't signed the license agreement, can you check?

2021-04-07 12:00 UTC, jeromelaban approved these changes

2021-04-07 19:16 UTC, merged