fix: Allow trailing 'px' for grid length
unoplatform/uno pull request #6626
Opened 2021-08-02 07:34 UTC by Youssef1313

GitHub Issue (If applicable): closes #5081

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

A trailing `px` suffix in grid length throws an exception.

## What is the new behavior?

A trailing `px` suffix is now allowed.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

2021-08-02 10:36 UTC, davidjohnoliver approved these changes

2021-08-02 11:44 UTC, jeromelaban approved these changes

2021-08-02 12:05 UTC, MartinZikmund requested changes
UWP supports any suffix (I tried `12asdfasfdv` 😀), so maybe this could be made more general - any non-number and non `.` character at the end would be ignored?

2021-08-02 12:38 UTC, Youssef1313 commented
@MartinZikmund This doesn't match what I see in a new UWP app:

![image](https://user-images.githubusercontent.com/31348972/127863001-6eeeadcf-d903-4044-af52-3c7e163ee136.png)

![image](https://user-images.githubusercontent.com/31348972/127863081-d1c68e57-1226-4580-b5d7-3e0702378b75.png)

2021-08-02 12:47 UTC, MartinZikmund commented
@Youssef1313 I saw that too, but weirdly enough, it still compiles and runs normally 😄

2021-08-02 12:53 UTC, Youssef1313 commented
> @Youssef1313 I saw that too, but weirdly enough, it still compiles and runs normally 😄

I thought it was supposed to not, since they show as "errors" (not warnings) in Visual Studio.
But I verified and indeed it compiles and run. Unclear to me what behavior Uno should have. The situation in UWP is like a semi-error case 😄 
Should we have a warning for non-px suffix?

My point is that: completely ignoring the suffix won't match UWP, and completely allowing it won't match UWP too.

2021-08-02 12:55 UTC, jeromelaban commented
Let's match what the designer reports as an error for now.

2021-08-02 13:43 UTC, MartinZikmund commented
@jeromelaban @Youssef1313 The weirdness continues 😀 . I tried some other things, which actually do not cause warning nor error:

- `12cm`
- `12pt`
- `12in`

Weirdly enough, the following do cause the "error":

- `12mm`
- `12epx`

So I would suggest to just ignore everything, as I have no idea what list of "fake units" is supported 😀

2021-08-02 13:45 UTC, davidjohnoliver commented
> Let's match what the designer reports as an error for now.

The only problem is that we might have to adjust it later to be more permissive if there's an 'error' in existing code (eg '300pix' instead of '300px'.)

I ran into a similar issue when importing the Fluent styles from WinUI 2 - there were extra curly brackets in one of the XAML files, which the designer complains about but the compiler does not. (The fix: https://github.com/unoplatform/uno/pull/3663/commits/96f4b450998a483e826e7ab02d28897fdbd9ae6c)

2021-08-02 14:06 UTC, Youssef1313 commented
> @jeromelaban @Youssef1313 The weirdness continues 😀 . I tried some other things, which actually do not cause warning nor error:
> 
> * `12cm`
> * `12pt`
> * `12in`
> 
> Weirdly enough, the following do cause the "error":
> 
> * `12mm`
> * `12epx`
> 
> So I would suggest to just ignore everything, as I have no idea what list of "fake units" is supported 😀

In WPF, these are only the extra supported units:

https://github.com/dotnet/wpf/blob/fedab1486c7c45508ca11a0761963c8d203337e1/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlGridLengthSerializer.cs#L275-L276

I expect that WPF is matching UWP for what units are allowed. But I'm not sure if these are indeed fake or if there is processing around them.

2021-08-02 14:43 UTC, MartinZikmund commented
@Youssef1313 seems I won the lottery that I accidentally found all supported ones 😀😀😀 . I tested it with WPF and UWP:

```
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="5in" />
        <RowDefinition Height="5px" />
        <RowDefinition Height="5pt" />
        <RowDefinition Height="5cm" />
        <RowDefinition Height="5" />
    </Grid.RowDefinitions>
    <Rectangle HorizontalAlignment="Stretch" VerticalAlignment="Stretch" Fill="Red" Grid.Row="0" />
    <Rectangle HorizontalAlignment="Stretch" VerticalAlignment="Stretch" Fill="Blue" Grid.Row="1" />
    <Rectangle HorizontalAlignment="Stretch" VerticalAlignment="Stretch" Fill="Violet" Grid.Row="2" />
    <Rectangle HorizontalAlignment="Stretch" VerticalAlignment="Stretch" Fill="CornflowerBlue" Grid.Row="3" />
    <Rectangle HorizontalAlignment="Stretch" VerticalAlignment="Stretch" Fill="Gray" Grid.Row="4" />
</Grid>
```

And the difference is huge 😀 :

![image](https://user-images.githubusercontent.com/1075116/127879555-31dd9e8c-e7c0-45cc-aa20-ecf2d0a28406.png)

So it seems UWP is just ignoring the units, while WPF is taking them into account.

2021-08-02 14:48 UTC, Youssef1313 commented
So we should ignore `px`, `cm`, in`, `pt`, and either have an error or warning for other suffixes, right?

2021-08-02 14:59 UTC, MartinZikmund commented
@Youssef1313 Yes, that sounds safe to me 👍

2021-08-03 14:05 UTC, MartinZikmund approved these changes

2021-08-03 14:05 UTC, MartinZikmund commented on src/SourceGenerators/XamlGenerationTests/Grid.Test.xaml
> +            <ColumnDefinition Width="300px" />
Can you add tests for the additional unit types here too please?

2021-08-03 22:19 UTC, merged