add support for inline MarkupExtension with named parameters
unoplatform/uno pull request #7993
Opened 2022-02-03 23:05 UTC by Xiaoy312

GitHub Issue (If applicable): closes #7947

## PR Type

What kind of change does this PR introduce?

- Bugfix
- Feature
## What is the new behavior?

- Binding with MarkupExtension block that contains separator `,` are now parsed correctly
- Custom markup can be used in binding

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information
```
{Binding Converter={StaticResource SomeNotImplementedConverter}, ConverterParameter={ext:MarkupWithArgs Prop1=1, Prop2=2}}
```
^ This was previously split into 3 parameters:
```
Converter={StaticResource SomeNotImplementedConverter}
ConverterParameter={ext:MarkupWithArgs Prop1=1
Prop2=2}
```

2022-02-04 02:31 UTC, Xiaoy312 commented on src/SourceGenerators/System.Xaml/System.Xaml/ParsedMarkupExtensionInfo.cs
> +		private static Regex BalancedMarkupBlockRegex = new Regex(@"
need more test cases against this regex

2022-02-04 19:12 UTC, jeromelaban commented on src/SourceGenerators/System.Xaml/System.Xaml/ParsedMarkupExtensionInfo.cs
> +			//}
Remove ?

2022-02-24 10:11 UTC, MartinZikmund approved these changes

2022-03-19 23:58 UTC, Xiaoy312 commented
update20220319: 
- scrapped my initial approach of using balanced regex for the reasons pointed out in comment, since it cannot handle quoted string with comma in it... and, replaced that with a "tokenizer"
- added more test cases to validate all 3 scenarios

2022-03-20 01:55 UTC, nventive-devops commented
The [build 42486](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=42486) found UI Test snapshots differences: `android-28-xamarin`: **56**, `android-28-xamarin-Snap`: **108**, `ios`: **47**, `ios-Snap`: **122**, `skia-gtk-screenshots`: **116**, `wasm`: **16**, `wasm-automated-net5.0-Benchmarks`: **0**, `wasm-automated-net5.0-Default`: **17**, `wasm-automated-net5.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **56** changed over 839

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Border_CornerRadius_BorderThickness_Border-CornerRadius-10-BorderThickness-10_0_0_0`
  - `Border_CornerRadius_BorderThickness_Border-CornerRadius-10-BorderThickness-10_0_10_10`
  - `Border_CornerRadius_GradientBrush_Screenshot`
  - `Border_CornerRadius_GradientBrush_UITests_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Gradient`
  - `Check_CornerRadius_Border_Basic_sample`
  - `Check_CornerRadius_Border_CornerRadius=5`
  - `Border_CornerRadius_BorderThickness_Border-CornerRadius-10-BorderThickness-0_0_0_0`
  - `Border_CornerRadius_BorderThickness_Border-CornerRadius-10-BorderThickness-10_0_0_10`
  - `Border_CornerRadius_BorderThickness_Border-CornerRadius-10-BorderThickness-10_10_10_10`
  - `Border_CornerRadius_BorderThickness_UITests_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_BorderThickness`
  - `Border_LinearGradient_Screenshot`
  - `Border_LinearGradient_UITests_Windows_UI_Xaml_Controls_BorderTests_Border_LinearGradientBrush`
  - `ComboBoxTests_Fullscreen_Popup_Generic_Closed`
  - `ComboBoxTests_Fullscreen_Popup_Generic_Opened`
  - `ComboBox_Dropdown_Background_ComboBox_open`
  - `CommandBar_LongTitle_Validation_CommandBar_-_LongTitle_-_3_-_Orientation_Portrait`
  - `FocusManager_GetFocusedElement_ComboBoxItem_Validation_FocusManager_-_GetFocusedElement_-_ComboBoxItem_-_2_-_After_Selection`
  - `FocusManager_GetFocusedElement_ComboBox_LostFocus_Validation_FocusManager_-_LostFocus_-_ComboBox_-_2_-_Click_outside`
  - `FocusManager_GetFocusedElement_ComboBox_Validation_FocusManager_-_GetFocusedElement_-_ComboBox_-_2_-_After_Selection`
  - `FocusManager_GetFocusedElement_TextBoxMultiLine_LostFocus_Validation_FocusManager_-_LostFocus_-_TextBoxMultiLine_-_2_-_Click_outside`
  </details>

* `android-28-xamarin-Snap`: **108** changed over 961

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Automation_UITests_Shared_Windows_UI_Xaml_Automation_AutomationProperties_Name_UITests_Shared_Windows_UI_Xaml_Automation_AutomationProperties_Name`
  - `Border_Border_CornerRadius_Binding_Uno_UI_Samples_UITests_BorderTestsControl_Border_CornerRadius_Binding`
  - `Border_Border_CornerRadius_BorderThickness_UITests_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_BorderThickness`
  - `Border_Border_CornerRadius_Uno_UI_Samples_UITests_BorderTestsControl_Border_CornerRadius`
  - `Border_Border_CornerRadius_with_Opacity_Uno_UI_Samples_UITests_BorderTestsControl_Border_CornerRadius_with_Opacity`
  - `Border_Border_Corner_Overlap_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerOverlap`
  - `Border_SimplewithNonUnifmormRadius_Uno_UI_Samples_UITests_BorderTestsControl_SimplewithNonUnifmormRadius`
  - `Border_Simple_with_Radius_Uno_UI_Samples_UITests_BorderTestsControl_Simple_with_Radius`
  - `Border_UITests_Windows_UI_Xaml_Controls_BorderTests_Border_LinearGradientBrush_UITests_Windows_UI_Xaml_Controls_BorderTests_Border_LinearGradientBrush`
  - `Border_UniformThicknessandNonUniformRadius_Uno_UI_Samples_UITests_BorderTestsControl_UniformThicknessandNonUniformRadius`
  - `Clipping_UITests_Shared_Windows_UI_Xaml_Clipping_ClippingRoundedCorners_UITests_Shared_Windows_UI_Xaml_Clipping_ClippingRoundedCorners`
  - `Border_Border_CornerRadius_Alignments_Uno_UI_Samples_UITests_BorderTestsControl_Border_CornerRadius_Alignments`
  - `Border_Border_CornerRadius_Gradient_UITests_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Gradient`
  - `Border_Circle_Uno_UI_Samples_UITests_BorderTestsControl_Circle`
  - `Border_NonUniformThicknessandRadius_Uno_UI_Samples_UITests_BorderTestsControl_NonUniformThicknessandRadius`
  - `Border_OnepxThicknessandRadiusAndTextBlock_Uno_UI_Samples_UITests_BorderTestsControl_OnepxThicknessandRadiusAndTextBlock`
  - `Border_OnepxThicknessandRadius_Uno_UI_Samples_UITests_BorderTestsControl_OnepxThicknessandRadius`
  - `Border_Uniform_Thickness_and_Large_Radius_Uno_UI_Samples_UITests_BorderTestsControl_Uniform_Thickness_and_Large_Radius`
  - `Border_Uniform_Thickness_and_Small_Radius_Uno_UI_Samples_UITests_BorderTestsControl_Uniform_Thickness_and_Small_Radius`
  - `Border_ZeroThicknessWithRadius_Uno_UI_Samples_UITests_BorderTestsControl_ZeroThicknessWithRadius`
  </details>

* `ios`: **47** changed over 290

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Check_ListView_Swallows_Measure_after_scroll`
  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `ListView_ObservableCollection_Creation_Count_Added`
  - `ListView_ObservableCollection_Creation_Count_Added_above`
  - `ListView_ObservableCollection_Creation_Count_Removed_above`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `ListView_ObservableCollection_Creation_Count_Scrolled1`
  - `ListView_ObservableCollection_Creation_Count_Scrolled2`
  - `PasswordBox_RevealInScrollViewer_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-1`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-2`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-1`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-2`
  - `Screenshots_Image_Stretch_Alignment_Bigger_Mode-3`
  </details>

* `ios-Snap`: **122** changed over 952

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Border_AutoBorderStretchwithleftmargin_Uno_UI_Samples_UITests_BorderTestsControl_AutoBorderStretchwithleftmargin`
  - `Border_BorderCenteredwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderCenteredwithmargins`
  - `Border_BorderLeftwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderLeftwithmargins`
  - `Border_BorderTopwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderTopwithmargins`
  - `Border_Border_Simple_No_Background_With_Content_Border_With_Background_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_No_Background_With_Content_Border_With_Background`
  - `Border_Border_Simple_No_Background_With_TextBox_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_No_Background_With_TextBox`
  - `Border_Border_Simple_with_non_Uniform_Thickness_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_with_non_Uniform_Thickness`
  - `Border_Border_Simple_with_Opacity_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_with_Opacity`
  - `Border_NonUniformThicknessandRadius_Uno_UI_Samples_UITests_BorderTestsControl_NonUniformThicknessandRadius`
  - `ButtonTestsControl_Button_Opacity_Automated_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Button_Opacity_Automated`
  - `Button_Custom_Button_With_ContentTemplate_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Custom_Button_With_ContentTemplate`
  - `Button_Hyperlink_CanExecute_False_nVentive_Umbrella_Views_UI_Samples_Content_UITests_ButtonTestsControl_Hyperlink_CanExecute_False`
  - `Butto [...]

2022-03-20 01:56 UTC, nventive-devops commented
The [build 42487](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=42487) found UI Test snapshots differences: `android-28-xamarin`: **61**, `android-28-xamarin-Snap`: **105**, `ios`: **47**, `ios-Snap`: **106**, `skia-gtk-screenshots`: **127**, `wasm`: **19**, `wasm-automated-net5.0-Benchmarks`: **0**, `wasm-automated-net5.0-Default`: **20**, `wasm-automated-net5.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **61** changed over 839

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Border_CornerRadius_BorderThickness_Border-CornerRadius-10-BorderThickness-10_0_0_0`
  - `Border_CornerRadius_BorderThickness_Border-CornerRadius-10-BorderThickness-10_0_10_10`
  - `Border_CornerRadius_BorderThickness_Border-CornerRadius-10-BorderThickness-10_10_10_10`
  - `Border_CornerRadius_GradientBrush_Screenshot`
  - `Border_CornerRadius_GradientBrush_UITests_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Gradient`
  - `Check_CornerRadius_Border_Basic_sample`
  - `Check_CornerRadius_Border_CornerRadius=5`
  - `Border_CornerRadius_BorderThickness_Border-CornerRadius-10-BorderThickness-0_0_0_0`
  - `Border_CornerRadius_BorderThickness_Border-CornerRadius-10-BorderThickness-10_0_0_10`
  - `Border_CornerRadius_BorderThickness_UITests_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_BorderThickness`
  - `Border_LinearGradient_Screenshot`
  - `Border_LinearGradient_UITests_Windows_UI_Xaml_Controls_BorderTests_Border_LinearGradientBrush`
  - `ComboBoxTests_Fullscreen_Popup_Generic_Closed`
  - `ComboBoxTests_Fullscreen_Popup_Generic_Opened`
  - `ComboBox_Dropdown_Background_ComboBox_open`
  - `FocusManager_GetFocusedElement_ComboBoxItem_Validation_FocusManager_-_GetFocusedElement_-_ComboBoxItem_-_2_-_After_Selection`
  - `FocusManager_GetFocusedElement_ComboBox_LostFocus_Validation_FocusManager_-_LostFocus_-_ComboBox_-_2_-_Click_outside`
  - `FocusManager_GetFocusedElement_ComboBox_Validation_FocusManager_-_GetFocusedElement_-_ComboBox_-_2_-_After_Selection`
  - `FocusManager_GetFocusedElement_TextBoxMultiLine_LostFocus_Validation_FocusManager_-_LostFocus_-_TextBoxMultiLine_-_2_-_Click_outside`
  - `FocusManager_GetFocusedElement_TextBoxMultiLine_Validation_FocusManager_-_GetFocusedElement_-_TextBoxMultiLine_-_1_-_Initial_State`
  </details>

* `android-28-xamarin-Snap`: **105** changed over 961

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Border_Border_CornerRadius_Binding_Uno_UI_Samples_UITests_BorderTestsControl_Border_CornerRadius_Binding`
  - `Border_Border_CornerRadius_BorderThickness_UITests_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_BorderThickness`
  - `Border_Border_CornerRadius_Uno_UI_Samples_UITests_BorderTestsControl_Border_CornerRadius`
  - `Border_Border_CornerRadius_with_Opacity_Uno_UI_Samples_UITests_BorderTestsControl_Border_CornerRadius_with_Opacity`
  - `Border_OnepxThicknessandRadiusAndTextBlock_Uno_UI_Samples_UITests_BorderTestsControl_OnepxThicknessandRadiusAndTextBlock`
  - `Border_OnepxThicknessandRadius_Uno_UI_Samples_UITests_BorderTestsControl_OnepxThicknessandRadius`
  - `Border_SimplewithNonUnifmormRadius_Uno_UI_Samples_UITests_BorderTestsControl_SimplewithNonUnifmormRadius`
  - `Border_Simple_with_Radius_Uno_UI_Samples_UITests_BorderTestsControl_Simple_with_Radius`
  - `Border_Uniform_Thickness_and_Large_Radius_Uno_UI_Samples_UITests_BorderTestsControl_Uniform_Thickness_and_Large_Radius`
  - `Border_Uniform_Thickness_and_Small_Radius_Uno_UI_Samples_UITests_BorderTestsControl_Uniform_Thickness_and_Small_Radius`
  - `Border_ZeroThicknessWithRadius_Uno_UI_Samples_UITests_BorderTestsControl_ZeroThicknessWithRadius`
  - `Clipping_UITests_Shared_Windows_UI_Xaml_Clipping_ClippingRoundedCorners_UITests_Shared_Windows_UI_Xaml_Clipping_ClippingRoundedCorners`
  - `Automation_UITests_Shared_Windows_UI_Xaml_Automation_AutomationProperties_Name_UITests_Shared_Windows_UI_Xaml_Automation_AutomationProperties_Name`
  - `Border_Border_CornerRadius_Alignments_Uno_UI_Samples_UITests_BorderTestsControl_Border_CornerRadius_Alignments`
  - `Border_Border_CornerRadius_Gradient_UITests_Windows_UI_Xaml_Controls_BorderTests_Border_CornerRadius_Gradient`
  - `Border_Border_Corner_Overlap_UITests_Shared_Windows_UI_Xaml_Controls_BorderTests_Border_CornerOverlap`
  - `Border_Circle_Uno_UI_Samples_UITests_BorderTestsControl_Circle`
  - `Border_NonUniformThicknessandRadius_Uno_UI_Samples_UITests_BorderTestsControl_NonUniformThicknessandRadius`
  - `Border_UITests_Windows_UI_Xaml_Controls_BorderTests_Border_LinearGradientBrush_UITests_Windows_UI_Xaml_Controls_BorderTests_Border_LinearGradientBrush`
  - `Border_UniformThicknessandNonUniformRadius_Uno_UI_Samples_UITests_BorderTestsControl_UniformThicknessandNonUniformRadius`
  </details>

* `ios`: **47** changed over 290

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `ListView_ChangingText_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Changing_Text`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_Collapsed_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_Expanded_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_Initial_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithMultipleItems_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Expandable_Item_Large`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithSingleItem_Validation_Collapsed_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithSingleItem_Validation_Expanded_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithSingleItem_Validation_Initial_State`
  - `ListView_ExpandableItemLarge_ExpandHeaderWithSingleItem_Validation_SamplesApp_Windows_UI_Xaml_Controls_ListView_ListView_Expandable_Item_Large`
  - `ContentPresenter_Template_Uno_UI_Samples_Content_UITests_ContentPresenter_ContentPresenter_Template`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `PasswordBox_RevealInScrollViewer_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-1`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-2`
  </details>

* `ios-Snap`: **106** changed over 952

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Animations_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background_UITests_Windows_UI_Xaml_Media_Animation_ColorAnimation_Background`
  - `AutoSuggestBox_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description_UITests_Windows_UI_Xaml_Controls_AutoSuggestBoxTests_AutoSuggestBox_Description`
  - `Border_BorderCenteredwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderCenteredwithmargins`
  - `Border_BorderLeftwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderLeftwithmargins`
  - `Border_BorderTopwithmargins_Uno_UI_Samples_UITests_BorderTestsControl_BorderTopwithmargins`
  - `Border_Border_Simple_No_Background_With_Content_Border_With_Background_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_No_Background_With_Content_Border_With_Background`
  - `Border_Border_Simple_No_Background_With_TextBox_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_No_Background_With_TextBox`
  - `Border_Border_Simple_with_non_Uni [...]

2022-03-20 12:35 UTC, xperiandri requested changes
I propose using modern C# inderxers syntax for extracting substrings as it simplifies code

2022-03-20 12:35 UTC, xperiandri commented on src/SourceGenerators/System.Xaml/System.Xaml/ParsedMarkupExtensionInfo.cs
> +			if (raw[raw.Length - 1] != '}')
```suggestion
			if (raw[^1] != '}')
```

2022-03-20 12:35 UTC, xperiandri commented on src/SourceGenerators/System.Xaml/System.Xaml/ParsedMarkupExtensionInfo.cs
> +			var name = nameSeparatorIndex != -1 ? raw.Substring(1, nameSeparatorIndex - 1) : raw.Substring(1, raw.Length - 2);
```suggestion
			var name = nameSeparatorIndex != -1 ? raw[1..(nameSeparatorIndex - 1)] : raw[1..^2];
```

2022-03-20 12:35 UTC, xperiandri commented on src/SourceGenerators/System.Xaml/System.Xaml/ParsedMarkupExtensionInfo.cs
> +			var valueWithoutBinding = raw.Substring(nameSeparatorIndex + 1, raw.Length - 1 - (nameSeparatorIndex + 1));
Probably `nameSeparatorIndex + 1` can be named somehow and cached into a variable
```suggestion
			var valueWithoutBinding = raw[(nameSeparatorIndex + 1)..^(1 + (nameSeparatorIndex + 1))];
```

2022-03-20 12:35 UTC, xperiandri commented on src/SourceGenerators/System.Xaml/System.Xaml/ParsedMarkupExtensionInfo.cs
> +					yield return vargs.Substring(lastSliceIndex + 1, i - lastSliceIndex - 1).Trim();
```suggestion
					yield return vargs[(lastSliceIndex + 1)..(i - lastSliceIndex - 1)].Trim();
```

2022-03-20 12:35 UTC, xperiandri commented on src/SourceGenerators/System.Xaml/System.Xaml/ParsedMarkupExtensionInfo.cs
> +			yield return vargs.Substring(lastSliceIndex + 1).Trim();
```suggestion
			yield return vargs[(lastSliceIndex + 1)..].Trim();
```

2022-03-20 12:37 UTC, xperiandri commented
Also, this code can be drastically simplified using [FParsec](http://www.quanttec.com/fparsec/) library

2022-03-22 02:48 UTC, jeromelaban commented
There are some issues, but it looks like the unit tests for the System.Xaml assemblies are not run properly. They should be included somehow by this: https://github.com/unoplatform/uno/blob/a9496507a82482ed85d134ba545241ddb2824123/build/ci/.azure-devops-unit-tests.yml#L55-L60

2022-03-22 20:22 UTC, Xiaoy312 commented
Uno.Xaml.Tests are not being picked up, not because of the `testAssemblyVer2` filter rules
but because it was compiled for net462 and the test runner expected net461 for some reason:

> ##[warning]DiscoveryMessage : Test run detected DLL(s) which were built for different framework and platform versions. Following DLL(s) do not match current settings, which are .NETFramework,Version=v4.6.1 framework and X86 platform.
> ...
> Uno.Xaml.Tests.dll is built for Framework .NETFramework,Version=v4.6.2 and Platform AnyCPU.

I have dropped the TargetFramework for that project, and it compiled locally.
Will see how CI like it~

2022-03-23 01:08 UTC, nventive-devops commented
The [build 42664](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=42664) found UI Test snapshots differences: `android-28-xamarin`: **27**, `android-28-xamarin-Snap`: **16**, `ios`: **45**, `ios-Snap`: **111**, `skia-gtk-screenshots`: **95**, `wasm`: **7**, `wasm-automated-net5.0-Benchmarks`: **0**, `wasm-automated-net5.0-Default`: **3**, `wasm-automated-net5.0-RuntimeTests`: **0**

<details>
<summary>Details</summary>


* `android-28-xamarin`: **27** changed over 841

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ComboBoxTests_Fullscreen_Popup_Generic_Closed`
  - `ComboBoxTests_Fullscreen_Popup_Generic_Opened`
  - `ComboBox_Dropdown_Background_ComboBox_open`
  - `FocusManager_GetFocusedElement_ComboBox_Validation_FocusManager_-_GetFocusedElement_-_ComboBox_-_2_-_After_Selection`
  - `FocusManager_GetFocusedElement_TextBoxMultiLine_Validation_FocusManager_-_GetFocusedElement_-_TextBoxMultiLine_-_1_-_Initial_State`
  - `FocusManager_GetFocusedElement_TextBoxMultiLine_Validation_FocusManager_-_GetFocusedElement_-_TextBoxMultiLine_-_2_-_After_Selection`
  - `FocusManager_GetFocusedElement_TextBoxMultiLine_Validation_Uno_UI_Samples_Content_UITests_FocusTests_FocusManager_GetFocus_Automated`
  - `FocusManager_GetFocusedElement_ComboBoxItem_LostFocus_Validation_FocusManager_-_LostFocus_-_ComboBoxItem_-_2_-_Click_outside`
  - `FocusManager_GetFocusedElement_ComboBoxItem_Validation_FocusManager_-_GetFocusedElement_-_ComboBoxItem_-_2_-_After_Selection`
  - `FocusManager_GetFocusedElement_ComboBox_LostFocus_Validation_FocusManager_-_LostFocus_-_ComboBox_-_2_-_Click_outside`
  - `PopupWithOverlay_After`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `SelectionTest_UITests_Microsoft_UI_Xaml_Controls_RadioButtonsTests_RadioButtonsPage`
  - `SequentialAnimations_SamplesApp_Windows_UI_Xaml_Media_Animation_SequentialAnimationsPage`
  - `TestProgressRing_InitialState_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRing_Features`
  - `TimePicker_Header_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_Header`
  - `WebView_NavigateToAnchor_click_anchor`
  - `WebView_NavigateToAnchor_Initial`
  - `WebView_NavigateToAnchor_navigate_to_anchor`
  </details>

* `android-28-xamarin-Snap`: **16** changed over 961

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ComboBox_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_DropDownPlacement_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_DropDownPlacement`
  - `Default_UITests_Windows_UI_Xaml_DragAndDrop_DragDrop_TestPage_UITests_Windows_UI_Xaml_DragAndDrop_DragDrop_TestPage`
  - `GridTestsControl_CenteredGridinGridwiththreefixedsizechildren_Uno_UI_Samples_Content_UITests_GridTestsControl_CenteredGridinGridwiththreefixedsizechildren`
  - `Image_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Formats_UITests_Windows_UI_Xaml_Controls_ImageTests_Image_Formats`
  - `Progress_UITests_Microsoft_UI_Xaml_Controls_ProgressBar_WinUIProgressBarSimple_UITests_Microsoft_UI_Xaml_Controls_ProgressBar_WinUIProgressBarSimple`
  - `Progress_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRingPage_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRingPage`
  - `Progress_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRing_CustomSources_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRing_CustomSources`
  - `Progress_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRing_Features_UITests_Microsoft_UI_Xaml_Controls_ProgressRing_WinUIProgressRing_Features`
  - `Progress_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `TabView_UITests_Microsoft_UI_Xaml_Controls_TabViewTests_TabViewPage_UITests_Microsoft_UI_Xaml_Controls_TabViewTests_TabViewPage`
  - `TextBox_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll`
  - `TimePicker_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_Header_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_Header`
  - `Time_Picker_TimePicker_TimePickerFlyoutStyle_UITests_Windows_UI_Xaml_Controls_TimePicker_TimePicker_TimePickerFlyoutStyle`
  - `WebView_WebView_WithHeaders_Uno_UI_Samples_Content_UITests_WebView_WebView_WithHeaders`
  - `Windows_Devices_Geolocator_UITests_Shared_Windows_Devices_GeolocatorTests`
  - `UIElement_TransformToVisual_Simple_UITests_Shared_Windows_UI_Xaml_UIElementTests_TransformToVisual_Simple`
  </details>

* `ios`: **45** changed over 290

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `ImageStretch_None_Uno_UI_Samples_UITests_ImageTestsControl_Image_Stretch_None`
  - `Keyboard_Textbox_NoScrollViewer_Validation_0_-_Remove_Focus_on_normalTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_4_-_Remove_Focus_on_multilineTextBox`
  - `ListView_ObservableCollection_Creation_Count_Added`
  - `ListView_ObservableCollection_Creation_Count_Added_above`
  - `ListView_ObservableCollection_Creation_Count_Removed_above`
  - `BasicExpressionTest_UITests_Microsoft_UI_Xaml_Controls_NumberBoxTests_NumberBox_ExpressionTest`
  - `Keyboard_Textbox_NoScrollViewer_Validation_1_-_Remove_Focus_on_filledTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_2_-_Remove_Focus_on_placeholderTextTextBox`
  - `Keyboard_Textbox_NoScrollViewer_Validation_5_-_Remove_Focus_on_numberTextBox`
  - `ListView_ObservableCollection_Creation_Count_Scrolled1`
  - `ListView_ObservableCollection_Creation_Count_Scrolled2`
  - `PasswordBox_RevealInScrollViewer_Uno_UI_Samples_Content_UITests_TextBoxControl_PasswordBox_Reveal_Scroll`
  - `ProgressRing_IsEnabled_Running_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `ProgressRing_Visibility_Collapsed_UITests_Windows_UI_Xaml_Controls_ProgressRing_WindowsProgressRing_GH1220`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-1`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-2`
  - `Screenshots_Image_Stretch_Algmnt_Inf_Vertical_Mode-3`
  - `Screenshots_Image_Stretch_Alignment_Equal_Mode-0`
  - `Screenshots_Image_Stretch_Alignment_Smaller_Mode-1`
  </details>

* `ios-Snap`: **111** changed over 952

  <details>
  <summary>🚨🚨 Comparison Details (first 20) 🚨🚨</summary>

  - `Border_Border_Simple_with_non_Uniform_Thickness_Uno_UI_Samples_UITests_BorderTestsControl_Border_Simple_with_non_Uniform_Thickness`
  - `Border_NonUniformThicknessandRadius_Uno_UI_Samples_UITests_BorderTestsControl_NonUniformThicknessandRadius`
  - `ButtonTestsControl_Button_Opacity_Automated_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Button_Opacity_Automated`
  - `Button_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Custom_Button_With_ContentTemplate_And_StackPanel_Uno_UI_Samples_Content_UITests_ButtonTestsControl_Custom_Button_With_ContentTemplate_And_StackPanel`
  - `Clipping_SamplesApp_Windows_UI_Xaml_Clipping_XamlButtonWithClipping_SamplesApp_Windows_UI_Xaml_Clipping_XamlButtonWithClipping`
  - `Clipping_UITests_Shared_Windows_UI_Xaml_Clipping_ClippingToControlBounds_UITests_Shared_Windows_UI_Xaml_Clipping_ClippingToControlBounds`
  - `ComboBox_ComboBox_ItemsSource_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_ItemsSource`
  - `ComboBox_ComboBox_NativePopup_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_NativePopup`
  - `ComboBox_ComboBox_NoDataContext_UITests_Shared_Windows_UI_Xaml_Controls_ComboBox_ComboBox_NoDataContext`
  - `ComboBox_ComboBox_Picker_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_Picker`
  - `ComboBox_ComboBox_PlaceholderText_SamplesApp_Wasm_Windows_UI_Xaml_Controls_ComboBox_ComboBox_PlaceholderText`
  - `ComboBox_UITests_Shared_Wi [...]

2022-03-23 12:11 UTC, jeromelaban commented
That's great tests got picked up! Thanks :)

2022-03-23 12:11 UTC, jeromelaban approved these changes

2022-03-23 14:10 UTC, merged