Fix typo in documentation
unoplatform/uno pull request #9329
Opened 2022-07-20 23:29 UTC by Rarisma

GitHub Issue (If applicable): closes #

## PR Type

What kind of change does this PR introduce?

2022-07-27 04:13 UTC, nickrandolph approved these changes

2022-07-27 04:16 UTC, nickrandolph requested changes
Can you amend you commit comment to use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#specification). In this case, you can just add "docs: " as a prefix

2022-08-08 19:51 UTC, Rarisma commented
Done.

2022-08-10 13:49 UTC, jeromelaban approved these changes

2022-08-10 13:58 UTC, nickrandolph approved these changes

2022-08-10 13:58 UTC, merged